// ═══════════════════════════════════════════════════════════════════════
// NCERT General Awareness Question Bank for SSC CGL Tier-I
// 500+ High-Yield MCQs: Class 6-12 | Science, History, Polity, Geography, Economics
// ═══════════════════════════════════════════════════════════════════════
const NCERT_QS = [

// ──────────────────────────────────────────────────────────────
// PHYSICS (Class 8-10)
// ──────────────────────────────────────────────────────────────
{id:"ph01",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"easy",q:"What is the SI unit of Force?",opts:["Newton","Joule","Watt","Pascal"],ans:0,exp:"The SI unit of force is Newton (N). Force = mass × acceleration, so 1 N = 1 kg·m/s²."},
{id:"ph02",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"easy",q:"An object is said to be in uniform motion when it covers:",opts:["Equal distances in equal intervals of time","Unequal distances in equal intervals of time","Equal distances in unequal intervals of time","Variable speed in equal intervals"],ans:0,exp:"Uniform motion means constant speed — the body covers equal distances in equal time intervals."},
{id:"ph03",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"medium",q:"Which of the following is a vector quantity?",opts:["Speed","Distance","Mass","Displacement"],ans:3,exp:"Displacement is a vector quantity because it has both magnitude and direction. Speed, distance and mass are scalar quantities."},
{id:"ph04",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"medium",q:"Newton's Second Law of Motion gives the definition of:",opts:["Inertia","Force","Momentum","Velocity"],ans:1,exp:"Newton's 2nd Law: F = ma. This equation defines force as the product of mass and acceleration."},
{id:"ph05",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"hard",q:"What happens to the kinetic energy of an object if its speed is doubled?",opts:["Doubles","Triples","Quadruples","Remains same"],ans:2,exp:"KE = ½mv². Doubling speed (v→2v): KE = ½m(2v)² = 4×(½mv²). Kinetic energy quadruples."},
{id:"ph06",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"easy",q:"The value of acceleration due to gravity (g) on Earth's surface is approximately:",opts:["6.67 × 10⁻¹¹ m/s²","9.8 m/s²","8.9 m/s²","10.8 m/s²"],ans:1,exp:"g ≈ 9.8 m/s² on Earth's surface. G (universal gravitational constant) = 6.67 × 10⁻¹¹ N m²/kg²."},
{id:"ph07",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"easy",q:"The phenomenon responsible for the formation of a rainbow is:",opts:["Reflection","Refraction","Dispersion","Diffraction"],ans:2,exp:"A rainbow is formed by dispersion of sunlight by water droplets. Dispersion splits white light into its component colours due to varying refractive indices."},
{id:"ph08",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"medium",q:"According to Newton's Third Law, action and reaction forces:",opts:["Act on the same body","Are equal in magnitude and opposite in direction but act on different bodies","Are unequal in magnitude","Act in the same direction"],ans:1,exp:"Newton's 3rd Law: Every action has an equal and opposite reaction. These forces act on different bodies, so they don't cancel each other."},
{id:"ph09",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"medium",q:"The momentum of a body is defined as:",opts:["Force × time","Mass × velocity","Mass × acceleration","Force × distance"],ans:1,exp:"Momentum (p) = mass × velocity (p = mv). It is a vector quantity with SI unit kg·m/s."},
{id:"ph10",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"easy",q:"The SI unit of power is:",opts:["Joule","Newton","Watt","Pascal"],ans:2,exp:"Power = Work/Time. SI unit is Watt (W) = 1 Joule/second. James Watt (Scottish inventor) gave his name to this unit."},
{id:"ph11",subject:"Physics",cls:"Class 10",topic:"physics",difficulty:"easy",q:"Ohm's law states that current through a conductor is:",opts:["Directly proportional to resistance","Inversely proportional to voltage","Directly proportional to voltage at constant temperature","Equal to power divided by resistance"],ans:2,exp:"Ohm's Law: V = IR, so I = V/R. Current is directly proportional to voltage at constant temperature and resistance."},
{id:"ph12",subject:"Physics",cls:"Class 10",topic:"physics",difficulty:"medium",q:"In a series circuit, the total resistance is:",opts:["Less than the smallest resistance","Equal to average of all resistances","Sum of all individual resistances","Product of all resistances"],ans:2,exp:"In series combination: R_total = R₁ + R₂ + R₃ + ... The same current flows through all resistors."},
{id:"ph13",subject:"Physics",cls:"Class 10",topic:"physics",difficulty:"medium",q:"Which colour of light has the highest frequency?",opts:["Red","Yellow","Blue","Violet"],ans:3,exp:"Violet light has the highest frequency (shortest wavelength) in visible spectrum. VIBGYOR — Red has lowest frequency, Violet has highest."},
{id:"ph14",subject:"Physics",cls:"Class 10",topic:"physics",difficulty:"easy",q:"The focal length of a concave mirror is:",opts:["Positive","Negative","Zero","Depends on object position"],ans:1,exp:"By sign convention, focal length of a concave mirror is negative (f = R/2, and R is negative for concave mirror). Convex mirror has positive focal length."},
{id:"ph15",subject:"Physics",cls:"Class 10",topic:"physics",difficulty:"hard",q:"Which effect was used by Oersted to establish the relationship between electricity and magnetism?",opts:["A current-carrying conductor deflects a nearby compass needle","Magnets attract iron filings","Electric charge at rest creates magnetic field","Moving magnets create static charges"],ans:0,exp:"In 1820, Hans Christian Oersted discovered that a current-carrying wire deflects a nearby magnetic compass needle, proving that electric current creates a magnetic field."},
{id:"ph16",subject:"Physics",cls:"Class 10",topic:"physics",difficulty:"medium",q:"Fleming's Left Hand Rule is used to find the direction of:",opts:["Induced EMF","Magnetic field due to a wire","Force on a current-carrying conductor in a magnetic field","Current due to a moving magnet"],ans:2,exp:"Fleming's Left Hand Rule (for motors): If the forefinger points in the direction of the magnetic field and the middle finger in the direction of current, the thumb gives the direction of force on the conductor."},
{id:"ph17",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"easy",q:"Ultrasonic waves have a frequency:",opts:["Below 20 Hz","Between 20 Hz and 20000 Hz","Above 20000 Hz","Exactly 20000 Hz"],ans:2,exp:"Ultrasound has frequency above 20,000 Hz (20 kHz) — beyond the upper limit of human hearing. Infrasound is below 20 Hz. SONAR uses ultrasonic waves."},
{id:"ph18",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"medium",q:"The speed of sound in air at 25°C is approximately:",opts:["343 m/s","1500 m/s","3 × 10⁸ m/s","300 m/s"],ans:0,exp:"Speed of sound in air is approximately 343 m/s at 25°C. It increases with temperature. Speed of light = 3 × 10⁸ m/s; speed of sound in water ≈ 1500 m/s."},
{id:"ph19",subject:"Physics",cls:"Class 10",topic:"physics",difficulty:"easy",q:"The power of a lens is measured in:",opts:["Metres","Dioptre","Newton","Watt"],ans:1,exp:"Power of a lens P = 1/f (where f is focal length in metres). Unit of power is Dioptre (D). A convex lens has positive power; concave lens has negative power."},
{id:"ph20",subject:"Physics",cls:"Class 10",topic:"physics",difficulty:"medium",q:"Joule's heating effect of electric current states that heat produced is proportional to:",opts:["I²Rt","IRt","I²R/t","IR²t"],ans:0,exp:"Joule's Law of Heating: H = I²Rt, where I is current, R is resistance, and t is time. This is the basis of electric heaters, bulbs and fuses."},
{id:"ph21",subject:"Physics",cls:"Class 10",topic:"physics",difficulty:"medium",q:"Which type of mirror is used as rear-view mirror in vehicles?",opts:["Concave mirror","Plane mirror","Convex mirror","Bifocal mirror"],ans:2,exp:"Convex mirrors are used as rear-view mirrors because they provide a wider field of view and form virtual, erect and diminished images of objects behind the vehicle."},
{id:"ph22",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"easy",q:"The Law of Conservation of Energy states that:",opts:["Energy can be created from nothing","Energy can be destroyed completely","Total energy of an isolated system remains constant","Kinetic energy equals potential energy always"],ans:2,exp:"Law of Conservation of Energy: Energy cannot be created or destroyed; it can only be converted from one form to another. Total energy of an isolated system is constant."},
{id:"ph23",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"medium",q:"If mass of an object is doubled and velocity is kept same, the kinetic energy becomes:",opts:["Half","Same","Double","4 times"],ans:2,exp:"KE = ½mv². If mass doubles (2m) but v remains same: KE = ½(2m)v² = 2 × (½mv²). Kinetic energy doubles."},
{id:"ph24",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"easy",q:"The universal law of gravitation was given by:",opts:["Einstein","Newton","Galileo","Kepler"],ans:1,exp:"Sir Isaac Newton formulated the Universal Law of Gravitation: F = Gm₁m₂/r². G = 6.67 × 10⁻¹¹ N m²/kg². Kepler gave laws of planetary motion."},
{id:"ph25",subject:"Physics",cls:"Class 9",topic:"physics",difficulty:"medium",q:"Work done by a force is zero when:",opts:["Force is large","Displacement is in direction of force","Displacement is perpendicular to force","Mass of object is large"],ans:2,exp:"W = F·d·cosθ. When displacement is perpendicular to force, θ = 90°, cos90° = 0. So Work = 0. Example: carrying a bag horizontally — no work done against gravity."},

// ──────────────────────────────────────────────────────────────
// CHEMISTRY (Class 8-10)
// ──────────────────────────────────────────────────────────────
{id:"ch01",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"easy",q:"The pH of a neutral solution at 25°C is:",opts:["0","7","14","1"],ans:1,exp:"pH scale ranges from 0 to 14. pH 7 = neutral (pure water). pH < 7 = acidic. pH > 7 = basic/alkaline. As acidity increases, pH decreases."},
{id:"ch02",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"easy",q:"Which of the following is an example of a combination reaction?",opts:["CaCO₃ → CaO + CO₂","2H₂ + O₂ → 2H₂O","AgNO₃ + NaCl → AgCl + NaNO₃","Fe + CuSO₄ → FeSO₄ + Cu"],ans:1,exp:"Combination reaction: Two or more substances combine to form a single product. 2H₂ + O₂ → 2H₂O is a classic combination reaction. CaCO₃ → CaO + CO₂ is decomposition."},
{id:"ch03",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"In the reactivity series, which metal is the most reactive?",opts:["Iron","Aluminium","Potassium","Copper"],ans:2,exp:"Reactivity series (most to least reactive): K > Na > Ca > Mg > Al > Zn > Fe > Pb > (H) > Cu > Hg > Ag > Au. Potassium (K) is the most reactive metal."},
{id:"ch04",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"easy",q:"Sodium hydroxide (NaOH) is a:",opts:["Weak acid","Strong acid","Strong base","Weak base"],ans:2,exp:"NaOH (caustic soda) is a strong base. It completely ionises in water: NaOH → Na⁺ + OH⁻. Strong bases include NaOH, KOH, Ca(OH)₂. Ammonia (NH₃) is a weak base."},
{id:"ch05",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"Baking soda has the chemical formula:",opts:["Na₂CO₃","NaHCO₃","NaCl","NaOH"],ans:1,exp:"Baking soda = Sodium Bicarbonate = NaHCO₃. Washing soda = Na₂CO₃·10H₂O. Common salt = NaCl. Baking powder = NaHCO₃ + tartaric acid."},
{id:"ch06",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"Rusting of iron is an example of which type of chemical reaction?",opts:["Combination reaction","Decomposition reaction","Displacement reaction","Double displacement reaction"],ans:0,exp:"Rusting: 4Fe + 3O₂ + 6H₂O → 4Fe(OH)₃. Iron combines with oxygen and water (combination reaction). It is also an oxidation-reduction (redox) reaction."},
{id:"ch07",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"easy",q:"Carbon has the atomic number:",opts:["6","12","14","8"],ans:0,exp:"Carbon (C) has atomic number 6 (6 protons). Atomic mass = 12. Carbon forms the basis of organic chemistry and life. Oxygen has atomic number 8."},
{id:"ch08",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"hard",q:"Which of the following is a characteristic property of metals?",opts:["They are good insulators of electricity","They are non-malleable","They have high melting points generally and are good conductors of electricity","They form acidic oxides"],ans:2,exp:"Metals are generally good conductors of heat and electricity, malleable, ductile, lustrous, and have high melting points. Non-metals form acidic oxides; metals form basic oxides."},
{id:"ch09",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"Mendeleev's Periodic Law states that properties of elements are a periodic function of their:",opts:["Atomic number","Atomic mass","Number of neutrons","Valence electrons"],ans:1,exp:"Mendeleev's Periodic Law (1869): Properties of elements are a periodic function of their atomic masses. Modern Periodic Law (Moseley, 1913): Properties are a function of atomic number."},
{id:"ch10",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"easy",q:"The element present in all organic compounds is:",opts:["Nitrogen","Hydrogen","Carbon","Oxygen"],ans:2,exp:"All organic compounds contain carbon. Carbon's ability to form 4 covalent bonds and bond with itself (catenation) makes it unique. Carbon compounds include carbohydrates, proteins, fats, DNA."},
{id:"ch11",subject:"Chemistry",cls:"Class 9",topic:"chemistry",difficulty:"medium",q:"Which law states that matter cannot be created nor destroyed in a chemical reaction?",opts:["Law of Definite Proportions","Law of Conservation of Mass","Law of Multiple Proportions","Dalton's Atomic Theory"],ans:1,exp:"Law of Conservation of Mass (Lavoisier): In a chemical reaction, total mass of reactants equals total mass of products. Mass is neither created nor destroyed."},
{id:"ch12",subject:"Chemistry",cls:"Class 9",topic:"chemistry",difficulty:"easy",q:"An atom of sodium has how many electrons in its outermost shell?",opts:["1","2","7","8"],ans:0,exp:"Sodium (Na, atomic number 11) has electronic configuration 2,8,1. It has 1 electron in its outermost (third) shell. This is why Na readily loses 1 electron to form Na⁺."},
{id:"ch13",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"Ethanol (C₂H₅OH) belongs to which homologous series?",opts:["Alkanes","Alkenes","Alkynes","Alcohols"],ans:3,exp:"Ethanol (C₂H₅OH) is an alcohol. The functional group of alcohols is -OH. Alkanes have C-C single bonds, alkenes have C=C double bonds, alkynes have C≡C triple bonds."},
{id:"ch14",subject:"Chemistry",cls:"Class 8",topic:"chemistry",difficulty:"easy",q:"The ignition temperature of a substance is:",opts:["Temperature at which it melts","Temperature at which it starts burning without any external flame","Boiling point of the substance","Temperature at which it dissolves"],ans:1,exp:"Ignition temperature is the minimum temperature at which a substance starts burning spontaneously without any external flame. Substances with lower ignition temperature are more flammable."},
{id:"ch15",subject:"Chemistry",cls:"Class 8",topic:"chemistry",difficulty:"easy",q:"Which type of coal has the highest carbon content?",opts:["Peat","Lignite","Bituminous","Anthracite"],ans:3,exp:"Anthracite coal has the highest carbon content (92-98%). Order: Peat < Lignite < Bituminous < Anthracite (in terms of carbon content and calorific value). Peat is the lowest grade."},
{id:"ch16",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"hard",q:"Plaster of Paris is obtained by heating:",opts:["CaCO₃","CaSO₄·2H₂O","Ca(OH)₂","CaO"],ans:1,exp:"Plaster of Paris = CaSO₄·½H₂O, obtained by heating gypsum (CaSO₄·2H₂O) at 100-120°C. It sets hard when mixed with water. Used in dentistry, sculpture and construction."},
{id:"ch17",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"Which gas is produced when zinc reacts with dilute sulphuric acid?",opts:["Oxygen","Carbon dioxide","Hydrogen","Nitrogen"],ans:2,exp:"Zn + H₂SO₄ → ZnSO₄ + H₂↑. Hydrogen gas is produced when active metals (Zn, Fe, Mg) react with dilute acids. This is a displacement reaction."},
{id:"ch18",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"The process of obtaining metals from their ores is called:",opts:["Refining","Smelting","Metallurgy","Leaching"],ans:2,exp:"Metallurgy is the science and technology of extracting metals from their ores and preparing them for use. Steps include: concentration of ore → reduction → refining."},
{id:"ch19",subject:"Chemistry",cls:"Class 9",topic:"chemistry",difficulty:"easy",q:"Atoms of the same element having different mass numbers are called:",opts:["Isobars","Isotopes","Ions","Allotropes"],ans:1,exp:"Isotopes: Same atomic number (same element) but different mass numbers (different neutrons). E.g., Carbon-12 and Carbon-14. Isobars have same mass number but different atomic numbers."},
{id:"ch20",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"Which of the following is a soap?",opts:["C₂H₅OH","CH₃COOH","C₁₇H₃₅COONa","C₆H₁₂O₆"],ans:2,exp:"Soap is the sodium or potassium salt of a long-chain carboxylic acid (fatty acid). C₁₇H₃₅COONa is sodium stearate — a common soap. Soaps have hydrophilic heads and hydrophobic tails."},
{id:"ch21",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"hard",q:"In the modern periodic table, the properties of elements repeat after every:",opts:["2 elements in all periods","8 elements","Number of elements equal to atomic number of noble gas in that period","10 elements"],ans:2,exp:"Properties repeat periodically based on electronic configuration. Period ends at noble gases (He=2, Ne=10, Ar=18, Kr=36...). Elements in same group (column) have similar properties."},
{id:"ch22",subject:"Chemistry",cls:"Class 8",topic:"chemistry",difficulty:"easy",q:"Fossil fuels are formed from:",opts:["Chemical reactions in factories","Decomposition of dead organisms over millions of years","Evaporation of seawater","Burning of wood"],ans:1,exp:"Fossil fuels (coal, petroleum, natural gas) are formed from the remains of dead organisms (plants and animals) buried under Earth for millions of years under high temperature and pressure."},
{id:"ch23",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"Bleaching powder has the chemical name:",opts:["Calcium chloride","Calcium hypochlorite","Calcium carbonate","Calcium oxide"],ans:1,exp:"Bleaching powder = Calcium hypochlorite = Ca(OCl)Cl or Ca(ClO)Cl. Made by passing Cl₂ over slaked lime Ca(OH)₂. Used as disinfectant, bleaching agent."},
{id:"ch24",subject:"Chemistry",cls:"Class 10",topic:"chemistry",difficulty:"medium",q:"Saponification is the process of:",opts:["Making soap by hydrolysis of fats with alkali","Making sugar from starch","Making alcohol by fermentation","Making nylon from amides"],ans:0,exp:"Saponification: Fat/oil + NaOH/KOH → Soap + Glycerol. This hydrolysis of esters (fats are esters) in alkaline medium gives soap. Named after 'sapo' (Latin for soap)."},
{id:"ch25",subject:"Chemistry",cls:"Class 9",topic:"chemistry",difficulty:"easy",q:"The number of particles in one mole of a substance is known as:",opts:["Planck's number","Boltzmann number","Avogadro's number","Faraday's number"],ans:2,exp:"Avogadro's Number = 6.022 × 10²³. One mole of any substance contains 6.022 × 10²³ particles (atoms/molecules/ions). Named after Amedeo Avogadro."},

// ──────────────────────────────────────────────────────────────
// BIOLOGY (Class 8-10)
// ──────────────────────────────────────────────────────────────
{id:"bi01",subject:"Biology",cls:"Class 8",topic:"biology",difficulty:"easy",q:"The powerhouse of the cell is:",opts:["Nucleus","Chloroplast","Mitochondria","Ribosome"],ans:2,exp:"Mitochondria are called the powerhouse of the cell because they produce ATP (energy) through cellular respiration. They have their own DNA. Plant cells also have chloroplasts."},
{id:"bi02",subject:"Biology",cls:"Class 8",topic:"biology",difficulty:"easy",q:"Which organelle controls all cell activities?",opts:["Mitochondria","Cell Wall","Nucleus","Vacuole"],ans:2,exp:"The nucleus is the control centre of the cell. It contains chromosomes (DNA) which carry genetic information and control all cellular activities. It is bound by a nuclear membrane."},
{id:"bi03",subject:"Biology",cls:"Class 8",topic:"biology",difficulty:"medium",q:"Cell wall in plant cells is made up of:",opts:["Protein","Cellulose","Chitin","Starch"],ans:1,exp:"Plant cell wall is made of cellulose (a polysaccharide). It provides rigidity and protection. Fungal cell walls are made of chitin. Animal cells have no cell wall."},
{id:"bi04",subject:"Biology",cls:"Class 9",topic:"biology",difficulty:"medium",q:"Which type of tissue is responsible for the growth of plants at the tips of roots and shoots?",opts:["Permanent tissue","Meristematic tissue","Epithelial tissue","Connective tissue"],ans:1,exp:"Meristematic tissue consists of actively dividing cells found at the growing tips (apical meristem), lateral regions (lateral meristem), and between nodes (intercalary meristem)."},
{id:"bi05",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"easy",q:"The overall equation for photosynthesis is:",opts:["C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O","6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂","CO₂ + H₂O → CH₂O + O","2H₂O + CO₂ → CH₄ + O₂"],ans:1,exp:"Photosynthesis: 6CO₂ + 6H₂O + Light energy → C₆H₁₂O₆ + 6O₂. Occurs in chloroplasts. Light energy is converted to chemical energy (glucose). Oxygen is released as by-product."},
{id:"bi06",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"easy",q:"Which blood group is the universal donor?",opts:["A","B","AB","O"],ans:3,exp:"Blood group O (O-) is the universal donor — it can donate to all blood groups. Blood group AB is the universal recipient. Blood groups were discovered by Karl Landsteiner."},
{id:"bi07",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"medium",q:"Insulin is secreted by which organ?",opts:["Liver","Kidney","Pancreas","Thyroid"],ans:2,exp:"Insulin is secreted by the beta cells of Islets of Langerhans in the pancreas. It lowers blood glucose levels. Glucagon (alpha cells) raises blood glucose. Deficiency of insulin causes diabetes."},
{id:"bi08",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"easy",q:"DNA stands for:",opts:["Deoxyribonucleic Acid","Diribonucleic Acid","Double Nucleic Acid","Deoxyribose Nucleic Acid"],ans:0,exp:"DNA = Deoxyribonucleic Acid. It carries genetic information. Double helix structure proposed by Watson and Crick (1953). RNA = Ribonucleic Acid. DNA differs from RNA in having deoxyribose sugar instead of ribose."},
{id:"bi09",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"medium",q:"Mendel's Law of Segregation states that:",opts:["Alleles of different genes assort independently","Two alleles of a gene separate during gamete formation","Dominant trait always expressed","Traits are blended in offspring"],ans:1,exp:"Law of Segregation: The two alleles of a gene separate (segregate) during the formation of gametes, so each gamete carries only one allele for each character."},
{id:"bi10",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"easy",q:"The basic unit of heredity is:",opts:["Cell","Chromosome","Gene","DNA"],ans:2,exp:"A gene is the basic unit of heredity. Genes are specific sequences of DNA that code for proteins. They are located on chromosomes. Humans have approximately 20,000-25,000 genes."},
{id:"bi11",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"medium",q:"Which of the following is a non-biodegradable waste?",opts:["Vegetable peels","Paper","Plastic bags","Leaf litter"],ans:2,exp:"Plastic bags are non-biodegradable — they cannot be broken down by microorganisms naturally. Vegetable peels, paper, leaf litter are biodegradable. Non-biodegradable waste causes long-term pollution."},
{id:"bi12",subject:"Biology",cls:"Class 8",topic:"biology",difficulty:"easy",q:"Antibiotics are produced by:",opts:["Viruses","Bacteria and fungi","Algae","Protozoa"],ans:1,exp:"Antibiotics are chemical substances produced by bacteria and fungi that kill or inhibit the growth of other bacteria. Penicillin (from Penicillium fungus) was the first antibiotic discovered by Alexander Fleming in 1928."},
{id:"bi13",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"medium",q:"What is the 10% law in ecology?",opts:["10% of sunlight is absorbed by plants","Only 10% of energy is transferred from one trophic level to the next","10% of organisms survive predation","10% of species are herbivores"],ans:1,exp:"10% Law (Lindeman, 1942): Only 10% of energy at each trophic level is transferred to the next level. The remaining 90% is lost as heat, respiration, etc. This limits the length of food chains."},
{id:"bi14",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"easy",q:"The process of breathing in animals involves:",opts:["Inhalation and Exhalation","Only inhalation","Only exhalation","Photosynthesis and Respiration"],ans:0,exp:"Breathing (pulmonary ventilation) involves inhalation (breathing in O₂) and exhalation (breathing out CO₂). Cellular respiration is the chemical process that releases energy from glucose."},
{id:"bi15",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"hard",q:"Which of the following represents a food chain?",opts:["Grass → Fox → Rabbit","Grass → Rabbit → Fox","Fox → Rabbit → Grass","Rabbit → Grass → Fox"],ans:1,exp:"A food chain shows the flow of energy from producers to consumers. Grass (producer) → Rabbit (primary consumer) → Fox (secondary consumer). Energy flows from left to right."},
{id:"bi16",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"medium",q:"Adrenaline is secreted by which gland?",opts:["Thyroid","Pituitary","Adrenal","Parathyroid"],ans:2,exp:"Adrenaline (epinephrine) is secreted by the adrenal medulla (inner part of adrenal gland). It is the 'fight or flight' hormone — increases heart rate, blood pressure, and prepares body for emergency."},
{id:"bi17",subject:"Biology",cls:"Class 9",topic:"biology",difficulty:"easy",q:"Which organism was used by Mendel for his experiments?",opts:["Fruit fly","Pea plant","Maize","Wheat"],ans:1,exp:"Gregor Mendel (1822-1884) used the garden pea plant (Pisum sativum) for his genetics experiments. He studied 7 contrasting characters. He is called the 'Father of Genetics.'"},
{id:"bi18",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"medium",q:"The theory of Natural Selection was proposed by:",opts:["Gregor Mendel","Lamarck","Charles Darwin","Hugo de Vries"],ans:2,exp:"Charles Darwin proposed the theory of Natural Selection in 'On the Origin of Species' (1859). Organisms better adapted to environment survive and reproduce (Survival of the Fittest)."},
{id:"bi19",subject:"Biology",cls:"Class 8",topic:"biology",difficulty:"easy",q:"Which of the following is responsible for nitrogen fixation?",opts:["Penicillium","Rhizobium","Amoeba","Paramecium"],ans:1,exp:"Rhizobium bacteria live in root nodules of leguminous plants (beans, peas) and fix atmospheric nitrogen into ammonia. This enriches soil with nitrogen — natural biofertiliser."},
{id:"bi20",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"medium",q:"The ozone layer is found in which atmospheric layer?",opts:["Troposphere","Stratosphere","Mesosphere","Thermosphere"],ans:1,exp:"The ozone (O₃) layer is in the stratosphere, at 15-35 km altitude. It absorbs harmful UV radiation. CFCs (chlorofluorocarbons) destroy ozone — the reason for the ozone hole above Antarctica."},
{id:"bi21",subject:"Biology",cls:"Class 8",topic:"biology",difficulty:"easy",q:"What is the function of white blood cells (WBCs)?",opts:["Transport oxygen","Carry carbon dioxide","Fight infections and provide immunity","Help in blood clotting"],ans:2,exp:"WBCs (leukocytes) are the soldiers of the immune system. They fight bacteria, viruses and other pathogens. Different types: neutrophils (most common), lymphocytes (make antibodies), monocytes, eosinophils, basophils."},
{id:"bi22",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"medium",q:"Which hormone promotes growth in plants?",opts:["Auxin","Cytokinin","Gibberellin","Abscisic acid"],ans:2,exp:"Gibberellins promote stem elongation, germination and flowering. Auxins cause phototropism and geotropism. Cytokinins promote cell division. Abscisic acid (ABA) inhibits growth and promotes dormancy."},
{id:"bi23",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"hard",q:"Thyroxine is produced by the thyroid gland and requires which mineral?",opts:["Iron","Calcium","Iodine","Zinc"],ans:2,exp:"Thyroxine (T4) contains iodine. Iodine deficiency causes goitre (swelling of thyroid). Thyroxine regulates metabolic rate, growth, and development. Hypothyroidism (under-active thyroid) causes fatigue, weight gain."},
{id:"bi24",subject:"Biology",cls:"Class 9",topic:"biology",difficulty:"medium",q:"Which kingdom do mushrooms belong to?",opts:["Plantae","Animalia","Fungi","Protista"],ans:2,exp:"Mushrooms belong to kingdom Fungi. They are eukaryotic, heterotrophic (saprotrophic) organisms with cell walls made of chitin. Fungi include moulds, yeasts, and mushrooms."},
{id:"bi25",subject:"Biology",cls:"Class 10",topic:"biology",difficulty:"easy",q:"Excretion in human beings is carried out by:",opts:["Liver only","Kidneys only","Kidneys, skin, lungs and liver","Only skin"],ans:2,exp:"Excretion involves removal of metabolic waste. Kidneys (urine), skin (sweat), lungs (CO₂ + water), liver (bile). The nephron is the functional unit of the kidney."},

// ──────────────────────────────────────────────────────────────
// HISTORY — ANCIENT INDIA
// ──────────────────────────────────────────────────────────────
{id:"ha01",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"easy",q:"The Indus Valley Civilisation is also known as:",opts:["Vedic Civilisation","Harappan Civilisation","Aryan Civilisation","Dravidian Civilisation"],ans:1,exp:"The Indus Valley Civilisation is also called the Harappan Civilisation (after Harappa, the first site discovered). It flourished around 2500-1900 BCE in the Indus Valley region."},
{id:"ha02",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"easy",q:"The 'Great Bath' was discovered at which Indus Valley site?",opts:["Harappa","Lothal","Mohenjo-daro","Kalibangan"],ans:2,exp:"The Great Bath — an ancient public bathing facility — was found at Mohenjo-daro. Harappa was in Punjab (now Pakistan). Lothal (Gujarat) had the only known dockyard. Dholavira had unique water conservation systems."},
{id:"ha03",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"medium",q:"Which is the oldest of the four Vedas?",opts:["Samaveda","Yajurveda","Rigveda","Atharvaveda"],ans:2,exp:"Rigveda is the oldest and most important of the four Vedas. It contains 1,028 hymns (suktas) in Sanskrit. Samaveda contains musical chants, Yajurveda has sacrificial formulae, Atharvaveda has spells."},
{id:"ha04",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"easy",q:"Chandragupta Maurya founded the Maurya Empire in:",opts:["321 BCE","273 BCE","184 BCE","600 BCE"],ans:0,exp:"Chandragupta Maurya established the Maurya Empire in 321 BCE with the help of Kautilya (Chanakya). The Arthashastra, written by Kautilya, is an ancient text on statecraft and economic policy."},
{id:"ha05",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"easy",q:"The Kalinga War was fought by Ashoka in:",opts:["321 BCE","261 BCE","232 BCE","185 BCE"],ans:1,exp:"Ashoka fought the Kalinga War in 261 BCE. The massive bloodshed (over 1 lakh dead) moved Ashoka to convert to Buddhism and adopt the policy of Dhamma (non-violence, tolerance). He issued Rock Edicts and Pillar Edicts."},
{id:"ha06",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"medium",q:"Who wrote the Arthashastra?",opts:["Ashoka","Chandragupta Maurya","Kautilya/Chanakya","Bindusara"],ans:2,exp:"Arthashastra was written by Kautilya (also called Chanakya or Vishnugupta), the prime minister and advisor of Chandragupta Maurya. It is a treatise on statecraft, economic policy, and military strategy."},
{id:"ha07",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"medium",q:"The Gupta period is often called the 'Golden Age of India' because:",opts:["India had maximum gold reserves","There was great progress in art, literature, science and mathematics","All citizens were wealthy","India had the largest empire"],ans:1,exp:"The Gupta Period (4th-6th century CE) is called the Golden Age due to achievements in mathematics (Aryabhatta), astronomy, literature (Kalidasa's Shakuntala), philosophy, and art. Coin minting also advanced greatly."},
{id:"ha08",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"easy",q:"Aryabhatta is associated with which contribution?",opts:["Discovery of penicillin","Invention of zero and calculating value of π","Theory of gravity","Writing Arthashastra"],ans:1,exp:"Aryabhatta (476-550 CE), great mathematician-astronomer of Gupta period, calculated the value of π (pi) ≈ 3.1416, explained lunar eclipses, and proposed that Earth rotates on its axis."},
{id:"ha09",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"medium",q:"Who was the Chinese traveller who visited India during the reign of Chandragupta II?",opts:["Xuanzang (Hiuen Tsang)","Fa-Hien","Megasthenes","Marco Polo"],ans:1,exp:"Fa-Hien (Faxian) visited India during Chandragupta II's reign (380-415 CE) to collect Buddhist texts. Xuanzang visited during Harsha's reign (7th century). Megasthenes (Greek ambassador) visited during Chandragupta Maurya's time."},
{id:"ha10",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"medium",q:"The first Buddhist Council was held at:",opts:["Pataliputra","Vaishali","Rajagriha","Kundalvana"],ans:2,exp:"First Buddhist Council (483 BCE, after Buddha's death) was held at Rajagriha under king Ajatashatru. Second (383 BCE) at Vaishali. Third (250 BCE) at Pataliputra under Ashoka. Fourth (72 CE) at Kashmir under Kanishka."},
{id:"ha11",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"easy",q:"Buddhism was founded by:",opts:["Mahavira","Vardhamana","Siddhartha Gautama","Adi Shankaracharya"],ans:2,exp:"Buddhism was founded by Siddhartha Gautama (563-483 BCE) who achieved enlightenment (Nirvana) at Bodh Gaya under the Peepal tree and became the Buddha. He gave his first sermon at Sarnath (Dhammachakka Pavattana)."},
{id:"ha12",subject:"History",cls:"Class 6",topic:"history_ancient",difficulty:"medium",q:"The word 'Upanishads' literally means:",opts:["Sacred hymns","Sitting near devotedly","Sacrificial rituals","Holy scriptures"],ans:1,exp:"Upanishads means 'sitting near' (upa = near, ni = devotedly, shad = sit). These are philosophical texts discussing the nature of Brahman (ultimate reality) and Atman (soul). There are 108 Upanishads; the earliest date to 800-400 BCE."},

// ──────────────────────────────────────────────────────────────
// HISTORY — MEDIEVAL INDIA
// ──────────────────────────────────────────────────────────────
{id:"hm01",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"easy",q:"The Delhi Sultanate was established by:",opts:["Babur","Muhammad Ghori","Qutb-ud-din Aibak","Alauddin Khalji"],ans:2,exp:"Qutb-ud-din Aibak (a slave of Muhammad Ghori) established the Delhi Sultanate in 1206 CE and founded the Slave Dynasty (Mamluk Dynasty). The Qutub Minar in Delhi was begun during his reign."},
{id:"hm02",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"easy",q:"The First Battle of Panipat (1526) was fought between:",opts:["Akbar and Hemu","Babur and Ibrahim Lodi","Humayun and Sher Shah Suri","Babur and Rana Sanga"],ans:1,exp:"The First Battle of Panipat (1526) was between Babur and Ibrahim Lodi (last Lodi Sultan). Babur won using gunpowder and artillery — ended the Lodi Dynasty and established the Mughal Empire."},
{id:"hm03",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"medium",q:"Who introduced the Mansabdari system?",opts:["Babur","Humayun","Akbar","Jahangir"],ans:2,exp:"Akbar introduced the Mansabdari system — a grading system for military and civil officers (mansabdars) with ranks from 10 to 10,000. The system determined salary, status, and military obligation."},
{id:"hm04",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"easy",q:"Akbar's policy of Din-i-Ilahi was:",opts:["A new religion that Akbar founded combining elements of Islam, Hinduism, Christianity and Zoroastrianism","A tax on non-Muslims","A military order","A legal code"],ans:0,exp:"Din-i-Ilahi (Divine Faith) was founded by Akbar in 1582 — a syncretic religion combining elements from Islam, Hinduism, Zoroastrianism, Christianity and Jainism. It had few followers and ended with Akbar's death."},
{id:"hm05",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"easy",q:"The Taj Mahal was built by:",opts:["Akbar","Jahangir","Shah Jahan","Aurangzeb"],ans:2,exp:"The Taj Mahal was built by Mughal Emperor Shah Jahan (1628-1658) in memory of his wife Mumtaz Mahal who died in 1631. Located in Agra, it was completed in 1653. It is a UNESCO World Heritage Site."},
{id:"hm06",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"medium",q:"Who founded the Bhakti movement saint Kabir's religion?",opts:["He was a disciple of Ramananda","He founded a new religion","He followed strictly Islam","He was a Buddhist"],ans:0,exp:"Kabir Das (1440-1518) was a mystic poet and saint in the Bhakti movement. He was a disciple of Ramananda and rejected caste distinctions and religious rituals. His dohas (couplets) bridge Hindu-Muslim traditions."},
{id:"hm07",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"hard",q:"Alauddin Khalji's market control reforms included:",opts:["Free market economy","Fixed prices for goods in four markets (grain, cattle, cloth, general goods)","Abolition of all markets","Import of goods from China"],ans:1,exp:"Alauddin Khalji established four markets in Delhi: (1) grain market, (2) cloth market, (3) cattle and horse market, (4) general goods market. Each had a Shahna (superintendent) to enforce fixed prices. Revolutionary economic reform."},
{id:"hm08",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"easy",q:"Which Mughal emperor compiled the Ain-i-Akbari?",opts:["Akbar himself","Todar Mal","Abul Fazl","Birbal"],ans:2,exp:"Ain-i-Akbari (Institutes of Akbar) was written by Abul Fazl, one of Akbar's Navratnas. It is part of the Akbarnama and details Akbar's administration, military, economy, and culture."},
{id:"hm09",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"medium",q:"The Vijayanagara Empire's famous king who defeated the Bahmani Sultanate was:",opts:["Krishnadeva Raya","Harihara I","Bukka Raya","Devaraya II"],ans:0,exp:"Krishnadeva Raya (1509-1529) was the greatest ruler of the Vijayanagara Empire. He defeated the Bahmani rulers and expanded the empire. He was also a poet and author of Amuktamalyada (Telugu)."},
{id:"hm10",subject:"History",cls:"Class 7",topic:"history_medieval",difficulty:"medium",q:"The Second Battle of Panipat (1556) was fought between:",opts:["Akbar and Hemu","Humayun and Sher Shah Suri","Babur and Ibrahim Lodi","Aurangzeb and Dara Shikoh"],ans:0,exp:"The Second Battle of Panipat (1556) was between Akbar (aided by Bairam Khan) and Hemu (General of Muhammad Adil Shah). Akbar won, consolidating Mughal power in India. Hemu was killed in the battle."},

// ──────────────────────────────────────────────────────────────
// HISTORY — MODERN INDIA
// ──────────────────────────────────────────────────────────────
{id:"hmod01",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"easy",q:"Vasco da Gama arrived in India in:",opts:["1498","1600","1757","1526"],ans:0,exp:"Vasco da Gama (Portuguese explorer) arrived at Kozhikode (Calicut), Kerala in 1498, discovering the sea route to India. This opened direct European trade with India, bypassing Ottoman-controlled land routes."},
{id:"hmod02",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"easy",q:"The British East India Company was established in:",opts:["1498","1600","1757","1857"],ans:1,exp:"The British East India Company (EIC) was established on 31 December 1600 by a royal charter of Queen Elizabeth I. It began as a trading company and gradually became a political power in India."},
{id:"hmod03",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"easy",q:"The Battle of Plassey (1757) was fought between:",opts:["Marathas and British","Siraj-ud-daulah and Robert Clive","Hyder Ali and British","Tipu Sultan and Cornwallis"],ans:1,exp:"Battle of Plassey (1757): Robert Clive defeated Siraj-ud-daulah (Nawab of Bengal) with the help of Mir Jafar's betrayal. This established British political dominance in India and was the start of British Empire in India."},
{id:"hmod04",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"medium",q:"The Doctrine of Lapse was a policy under which annexation was done by:",opts:["Wellesley","Dalhousie","Cornwallis","Bentinck"],ans:1,exp:"Doctrine of Lapse was introduced by Lord Dalhousie (1848-1856). Under it, if a ruler died without a natural male heir, the state would 'lapse' (merge) into British territory. States annexed: Satara, Jhansi, Nagpur, Udaipur."},
{id:"hmod05",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"easy",q:"The Revolt of 1857 began at:",opts:["Delhi","Lucknow","Meerut","Kanpur"],ans:2,exp:"The 1857 Revolt (First War of Independence / Sepoy Mutiny) began on 10 May 1857 at Meerut. The immediate cause was the rumour that the cartridges of the new Enfield rifle were greased with cow and pig fat."},
{id:"hmod06",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"medium",q:"Who was the founder of the Brahmo Samaj?",opts:["Swami Vivekananda","Dayanand Saraswati","Raja Ram Mohan Roy","Jyotiba Phule"],ans:2,exp:"Raja Ram Mohan Roy founded the Brahmo Samaj in 1828 in Calcutta. He campaigned against Sati (widow immolation), which was abolished in 1829 by Lord William Bentinck. He is called the 'Father of Indian Renaissance.'"},
{id:"hmod07",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"easy",q:"Arya Samaj was founded by:",opts:["Swami Vivekananda","Dayanand Saraswati","Raja Ram Mohan Roy","Ramakrishna Paramhansa"],ans:1,exp:"Arya Samaj was founded by Swami Dayanand Saraswati in 1875 in Mumbai. Slogan: 'Back to the Vedas.' He advocated against idol worship, caste system, and child marriage. He wrote Satyarth Prakash."},
{id:"hmod08",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"easy",q:"The Indian National Congress (INC) was founded in:",opts:["1857","1885","1905","1919"],ans:1,exp:"INC was founded on 28 December 1885 by A.O. Hume (retired British ICS officer) along with Dadabhai Naoroji and Dinshaw Wacha. First session was in Bombay with W.C. Bonnerjee as the first president."},
{id:"hmod09",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"medium",q:"The partition of Bengal (1905) was done by:",opts:["Curzon","Dalhousie","Wellesley","Cornwallis"],ans:0,exp:"Lord Curzon partitioned Bengal in 1905 on the pretext of administrative efficiency, but the real motive was to weaken the nationalist movement by dividing Hindus and Muslims. This sparked the Swadeshi Movement."},
{id:"hmod10",subject:"History",cls:"Class 10",topic:"history_modern",difficulty:"easy",q:"The Rowlatt Act (1919) was opposed because it:",opts:["Imposed new taxes","Allowed detention without trial","Partitioned Bengal","Abolished the INC"],ans:1,exp:"Rowlatt Act (1919) empowered the government to detain political prisoners without trial. Gandhi called it the 'Black Act.' Protests against it led to the Jallianwala Bagh Massacre on 13 April 1919."},
{id:"hmod11",subject:"History",cls:"Class 10",topic:"history_modern",difficulty:"easy",q:"The Non-Cooperation Movement was launched in:",opts:["1905","1919","1920","1930"],ans:2,exp:"Gandhi launched the Non-Cooperation Movement in 1920-22. Features: boycott of British goods, schools, courts, legislatures; return of titles and honours. Ended abruptly after Chauri Chaura violence (February 1922)."},
{id:"hmod12",subject:"History",cls:"Class 10",topic:"history_modern",difficulty:"easy",q:"The Dandi March (Salt March) was conducted in:",opts:["1919","1920","1930","1942"],ans:2,exp:"Gandhi led the Dandi March (12 March - 6 April 1930) — a 240-mile march from Sabarmati Ashram to Dandi, Gujarat, to protest the salt tax. This launched the Civil Disobedience Movement."},
{id:"hmod13",subject:"History",cls:"Class 10",topic:"history_modern",difficulty:"easy",q:"'Do or Die' slogan is associated with:",opts:["Non-Cooperation Movement","Civil Disobedience","Quit India Movement","Swadeshi Movement"],ans:2,exp:"'Do or Die' (Karo ya Maro) was Gandhi's call during the Quit India Movement launched on 8 August 1942. Gandhi was arrested at Gowalia Tank, Bombay. This was the most decisive movement demanding immediate independence."},
{id:"hmod14",subject:"History",cls:"Class 10",topic:"history_modern",difficulty:"medium",q:"Who led the Indian National Army (INA)?",opts:["Bhagat Singh","Bal Gangadhar Tilak","Subhas Chandra Bose","Lala Lajpat Rai"],ans:2,exp:"Subhas Chandra Bose (Netaji) led the Indian National Army (INA/Azad Hind Fauj) from 1943. INA was formed by Rash Behari Bose. Netaji gave the slogan 'Dilli Chalo' and established the Provisional Government of Free India in Singapore."},
{id:"hmod15",subject:"History",cls:"Class 8",topic:"history_modern",difficulty:"medium",q:"Bal-Pal-Lal refers to:",opts:["Three British Governors","Three nationalist leaders of the Extremist faction","Three Mughal Emperors","Three social reformers"],ans:1,exp:"Bal-Pal-Lal: Bal Gangadhar Tilak, Bipin Chandra Pal, and Lala Lajpat Rai — the three leaders of the Extremist (Garam Dal) faction in INC. They believed in swaraj (self-rule) through active resistance, not mere petitions."},

// ──────────────────────────────────────────────────────────────
// GEOGRAPHY
// ──────────────────────────────────────────────────────────────
{id:"geo01",subject:"Geography",cls:"Class 6",topic:"geography",difficulty:"easy",q:"How many planets are there in the Solar System?",opts:["7","8","9","10"],ans:1,exp:"There are 8 planets in the Solar System: Mercury, Venus, Earth, Mars (inner/terrestrial planets), Jupiter, Saturn, Uranus, Neptune (outer/gas giants). Pluto was reclassified as a dwarf planet in 2006."},
{id:"geo02",subject:"Geography",cls:"Class 6",topic:"geography",difficulty:"easy",q:"The Tropic of Cancer passes through which Indian states?",opts:["Only 4 states","8 states","6 states","5 states"],ans:1,exp:"Tropic of Cancer (23.5°N) passes through 8 Indian states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram."},
{id:"geo03",subject:"Geography",cls:"Class 6",topic:"geography",difficulty:"easy",q:"India's Standard Time is ahead of GMT by:",opts:["5 hours","5 hours 30 minutes","6 hours","4 hours 30 minutes"],ans:1,exp:"Indian Standard Time (IST) = GMT + 5 hours 30 minutes (+5:30). IST is based on the 82.5°E longitude passing through Allahabad (Prayagraj). India has a single time zone."},
{id:"geo04",subject:"Geography",cls:"Class 6",topic:"geography",difficulty:"easy",q:"The International Date Line is approximately along the:",opts:["0° longitude","90°E longitude","180° longitude","90°W longitude"],ans:2,exp:"The International Date Line (IDL) runs approximately along the 180° meridian (anti-meridian). When you cross it westward, you gain a day; eastward, you lose a day. It zigzags to avoid landmasses."},
{id:"geo05",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"medium",q:"The Himalayan mountain range is classified as:",opts:["Block mountains","Fold mountains","Volcanic mountains","Residual mountains"],ans:1,exp:"Himalayas are young fold mountains formed by the collision of the Indo-Australian plate with the Eurasian plate. They are still rising (growing). Other examples: Alps, Andes, Rockies."},
{id:"geo06",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"easy",q:"The highest peak in India is:",opts:["Mount Everest","K2 (Godwin Austen)","Kanchenjunga","Nanda Devi"],ans:1,exp:"K2 (Godwin Austen, 8,611 m) in the Karakoram range is the highest peak entirely within India (administered by India). Kanchenjunga (8,586 m) in Sikkim is the highest peak within India's territory if K2 is in PoK."},
{id:"geo07",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"easy",q:"The Ganga river originates from:",opts:["Gangotri Glacier","Siachen Glacier","Mansarovar Lake","Yamunotri"],ans:0,exp:"The Ganga originates from Gangotri Glacier (Gomukh) in Uttarakhand at an altitude of 3,892 m. It is India's longest river (2,525 km). Yamuna originates from Yamunotri."},
{id:"geo08",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"medium",q:"Which type of soil is most suitable for cotton cultivation?",opts:["Alluvial soil","Laterite soil","Black (regur) soil","Sandy soil"],ans:2,exp:"Black soil (Regur soil) is most suitable for cotton cultivation. It is found in the Deccan Plateau (Maharashtra, Gujarat, MP). Black soil has high moisture retention capacity and is rich in iron, calcium, and magnesium."},
{id:"geo09",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"easy",q:"South-West Monsoon arrives in India approximately in:",opts:["March","June","September","December"],ans:1,exp:"The South-West Monsoon arrives at Kerala around 1 June and covers the entire country by mid-July. It brings about 70-80% of India's annual rainfall. It retreats between September and December."},
{id:"geo10",subject:"Geography",cls:"Class 7",topic:"geography",difficulty:"easy",q:"Which is the largest ocean in the world?",opts:["Atlantic Ocean","Indian Ocean","Arctic Ocean","Pacific Ocean"],ans:3,exp:"The Pacific Ocean is the largest ocean, covering more than 30% of Earth's surface (about 165 million km²). It is also the deepest (Mariana Trench, 11,034 m). The Indian Ocean is the third largest."},
{id:"geo11",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"medium",q:"The Thar Desert is located in which Indian state primarily?",opts:["Gujarat","Rajasthan","Haryana","Punjab"],ans:1,exp:"The Thar Desert (Great Indian Desert) is primarily in Rajasthan (also extends into Gujarat, Punjab and Haryana). It receives less than 150 mm of annual rainfall. The Indira Gandhi Canal brings water to this region."},
{id:"geo12",subject:"Geography",cls:"Class 7",topic:"geography",difficulty:"easy",q:"Tropical rainforests have which characteristic?",opts:["Sparse vegetation and extreme temperature variations","Dense vegetation, high rainfall, and biodiversity","Seasonal vegetation with annual drought","Only coniferous trees"],ans:1,exp:"Tropical rainforests (equatorial climate) receive rainfall >200 cm annually, have dense multi-layered vegetation, high biodiversity, and evergreen trees. Found near the Equator: Amazon basin, Congo basin, Southeast Asia."},
{id:"geo13",subject:"Geography",cls:"Class 6",topic:"geography",difficulty:"easy",q:"The equator passes through how many continents?",opts:["2","3","4","5"],ans:1,exp:"The Equator (0° latitude) passes through 3 continents: South America (Ecuador, Colombia, Brazil), Africa (Gabon, Congo, Uganda, Kenya, Somalia), and Asia (Indonesia)."},
{id:"geo14",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"medium",q:"The Brahmaputra river is known as 'Tsangpo' in:",opts:["Bangladesh","Bhutan","China (Tibet)","Myanmar"],ans:2,exp:"The Brahmaputra originates in Tibet (China) as the Tsangpo, enters Arunachal Pradesh as Dihang/Siang, then becomes Brahmaputra in Assam, and flows into Bangladesh as Jamuna before joining the Ganga delta."},
{id:"geo15",subject:"Geography",cls:"Class 10",topic:"geography",difficulty:"medium",q:"Which type of farming is practiced in the north-eastern states of India?",opts:["Intensive farming","Plantation farming","Jhum (shifting) cultivation","Commercial farming"],ans:2,exp:"Jhum cultivation (shifting agriculture / slash and burn) is practiced in north-eastern states (Nagaland, Mizoram, Meghalaya). Forests are cleared, crops grown for 2-3 years, then land is abandoned and a new plot cleared."},
{id:"geo16",subject:"Geography",cls:"Class 10",topic:"geography",difficulty:"easy",q:"India's largest coal-producing state is:",opts:["Chhattisgarh","Odisha","Jharkhand","West Bengal"],ans:2,exp:"Jharkhand is India's largest coal-producing state, followed by Chhattisgarh and Odisha. Major coalfields: Jharia and Bokaro (Jharkhand), Korba (Chhattisgarh), Talcher (Odisha), Singrauli (MP)."},
{id:"geo17",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"easy",q:"The Deccan Plateau is a:",opts:["Delta","Young fold mountain","Peninsular plateau","Coastal plain"],ans:2,exp:"The Deccan Plateau is a large peninsular plateau in southern India (south of Satpura and Vindhya ranges). It slopes gently eastward. The Western Ghats and Eastern Ghats form its edges. It is made of ancient rocks."},
{id:"geo18",subject:"Geography",cls:"Class 7",topic:"geography",difficulty:"medium",q:"Warm ocean currents originate near:",opts:["Polar regions","Equatorial regions","Mediterranean sea","Arctic ocean"],ans:1,exp:"Warm currents originate near the Equator and flow towards poles. Examples: Gulf Stream (Atlantic), Kuroshio (Pacific). Cold currents originate near poles and flow towards equator. They affect climate of coastal regions."},
{id:"geo19",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"medium",q:"The Western Ghats are also known as:",opts:["Sahyadri","Aravalli","Vindhyas","Satpura"],ans:0,exp:"The Western Ghats are also called Sahyadri. They run parallel to the west coast for about 1,600 km through Gujarat, Maharashtra, Goa, Karnataka, Tamil Nadu and Kerala. They are a UNESCO World Heritage Site and biodiversity hotspot."},
{id:"geo20",subject:"Geography",cls:"Class 9",topic:"geography",difficulty:"easy",q:"India's largest delta is:",opts:["Mahanadi delta","Krishna-Godavari delta","Ganga-Brahmaputra (Sundarbans) delta","Kaveri delta"],ans:2,exp:"The Ganga-Brahmaputra delta (Sundarbans) is the world's largest delta, shared between India and Bangladesh. It covers about 80,000 km². It is home to the Bengal tiger and mangrove forests."},

// ──────────────────────────────────────────────────────────────
// POLITY (Class 9-11)
// ──────────────────────────────────────────────────────────────
{id:"pol01",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"easy",q:"The Constitution of India was adopted on:",opts:["15 August 1947","26 November 1949","26 January 1950","2 October 1950"],ans:1,exp:"The Constitution was adopted by the Constituent Assembly on 26 November 1949 (Constitution Day). It came into force on 26 January 1950 (Republic Day). The Constituent Assembly took 2 years, 11 months and 18 days to draft it."},
{id:"pol02",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"easy",q:"Who is called the 'Father of the Indian Constitution'?",opts:["Jawaharlal Nehru","Sardar Patel","Dr. B.R. Ambedkar","Dr. Rajendra Prasad"],ans:2,exp:"Dr. B.R. Ambedkar was the Chairman of the Drafting Committee and is called the 'Father of the Indian Constitution.' Dr. Rajendra Prasad was the President of the Constituent Assembly."},
{id:"pol03",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"easy",q:"The Preamble of the Constitution declares India to be a:",opts:["Federal state with unitary features","Sovereign Socialist Secular Democratic Republic","Constitutional Monarchy","Confederation of states"],ans:1,exp:"The Preamble declares India a Sovereign (independent), Socialist (mixed economy), Secular (no state religion), Democratic (elected government), Republic (elected head of state). 'Socialist' and 'Secular' were added by the 42nd Amendment (1976)."},
{id:"pol04",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"easy",q:"Right to Constitutional Remedies is given under Article:",opts:["14","19","21","32"],ans:3,exp:"Article 32 gives the Right to Constitutional Remedies — the right to move the Supreme Court for enforcement of Fundamental Rights. Dr. Ambedkar called Article 32 the 'Heart and Soul of the Constitution.'"},
{id:"pol05",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"medium",q:"Fundamental Rights are contained in which Part of the Constitution?",opts:["Part II","Part III","Part IV","Part V"],ans:1,exp:"Fundamental Rights are in Part III of the Constitution (Articles 12-35). Part II = Citizenship, Part IV = DPSP, Part IV-A = Fundamental Duties. Originally 7 FRs; Right to Property removed by 44th Amendment (1978)."},
{id:"pol06",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"easy",q:"The maximum strength of the Rajya Sabha is:",opts:["250","245","552","543"],ans:0,exp:"Maximum strength of Rajya Sabha = 250 (238 elected + 12 nominated by President). Present strength = 245. Vice President is ex-officio Chairman of Rajya Sabha. Rajya Sabha is a permanent house — not subject to dissolution."},
{id:"pol07",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"easy",q:"The Speaker of the Lok Sabha is:",opts:["Appointed by the President","Elected by members of Lok Sabha","The Vice President","Nominated by the PM"],ans:1,exp:"The Speaker of Lok Sabha is elected by the members of the Lok Sabha from among themselves. The Speaker presides over Lok Sabha sessions, maintains order, and decides on money bills."},
{id:"pol08",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"medium",q:"The President of India is elected by:",opts:["All citizens of India directly","Only Rajya Sabha members","Elected members of Parliament and State Legislative Assemblies","All MPs and MLAs including nominated members"],ans:2,exp:"The President is elected by an electoral college comprising elected members of both Houses of Parliament (Lok Sabha + Rajya Sabha) and elected members of State Legislative Assemblies. Nominated members do NOT vote."},
{id:"pol09",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"easy",q:"Article 21 of the Constitution guarantees:",opts:["Right to Equality","Right to Freedom of Speech","Protection of Life and Personal Liberty","Right to Education"],ans:2,exp:"Article 21: 'No person shall be deprived of his life or personal liberty except according to procedure established by law.' It has been expanded by the Supreme Court to include many rights including right to livelihood, privacy, and dignified life."},
{id:"pol10",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"medium",q:"Which Article deals with the Right to Education?",opts:["Article 19","Article 21","Article 21A","Article 45"],ans:2,exp:"Article 21A (inserted by 86th Constitutional Amendment, 2002): Free and Compulsory Education for children between 6-14 years. The RTE Act was enacted in 2009 to give effect to this right."},
{id:"pol11",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"medium",q:"Fundamental Duties are contained in which Article?",opts:["Art 49","Art 50","Art 51","Art 51A"],ans:3,exp:"Fundamental Duties are in Article 51A (added by 42nd Amendment, 1976). Originally 10 duties; an 11th duty (promote education for children aged 6-14) was added by 86th Amendment (2002). Inspired by USSR Constitution."},
{id:"pol12",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"hard",q:"Which schedule contains the provisions regarding disqualification of Members of Parliament on the ground of defection?",opts:["7th Schedule","8th Schedule","10th Schedule","5th Schedule"],ans:2,exp:"10th Schedule (added by 52nd Amendment, 1985) contains the Anti-Defection Law. It disqualifies a member if they voluntarily give up party membership or vote against party directions. The Speaker decides on disqualification."},
{id:"pol13",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"medium",q:"The Union List (List I) in the 7th Schedule contains subjects on which:",opts:["State governments can make laws","Only Parliament can make laws","Both Parliament and States can make laws","Only local bodies can make laws"],ans:1,exp:"7th Schedule has 3 lists: Union List (97 subjects, only Parliament), State List (66 subjects, only States), Concurrent List (47 subjects, both). In case of conflict on Concurrent List, Parliament's law prevails."},
{id:"pol14",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"easy",q:"Article 356 relates to:",opts:["President's Rule in a State","Emergency due to war","Financial Emergency","National Emergency"],ans:0,exp:"Article 356: President's Rule (State Emergency) can be imposed in a state if the constitutional machinery fails. It requires approval of Parliament. First imposed in Punjab (1951). Maximum period: 3 years (with 6-month extensions)."},
{id:"pol15",subject:"Polity",cls:"Class 9",topic:"polity",difficulty:"medium",q:"The Election Commission is established under which Article?",opts:["Art 148","Art 315","Art 324","Art 280"],ans:2,exp:"Article 324 establishes the Election Commission of India. It is a permanent constitutional body responsible for superintendence, direction and control of elections to Parliament, State Legislatures, Presidency and Vice-Presidency."},

// ──────────────────────────────────────────────────────────────
// ECONOMICS (Class 9-12)
// ──────────────────────────────────────────────────────────────
{id:"eco01",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"easy",q:"GDP stands for:",opts:["Gross Domestic Product","General Development Plan","Gross Development Profit","Global Domestic Production"],ans:0,exp:"GDP (Gross Domestic Product) is the total monetary value of all goods and services produced within a country's borders in a specific time period. It is the most commonly used measure of economic size."},
{id:"eco02",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"medium",q:"The Reserve Bank of India was established in:",opts:["1947","1935","1969","1949"],ans:1,exp:"RBI was established on 1 April 1935 under the Reserve Bank of India Act, 1934. It was nationalised on 1 January 1949. First Governor: Sir Osborne Smith. Current function: regulating monetary policy, issuing currency, banker's bank."},
{id:"eco03",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"easy",q:"Which sector of the economy includes agriculture?",opts:["Tertiary sector","Secondary sector","Primary sector","Quaternary sector"],ans:2,exp:"Primary sector includes activities related to natural resources: agriculture, forestry, fishing, mining, quarrying. Secondary sector = manufacturing. Tertiary sector = services (banking, transport, trade)."},
{id:"eco04",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"medium",q:"The NITI Aayog replaced which body in 2015?",opts:["Reserve Bank of India","Finance Commission","Planning Commission","National Development Council"],ans:2,exp:"NITI Aayog (National Institution for Transforming India) replaced the Planning Commission on 1 January 2015. It focuses on cooperative federalism and acts as a think tank rather than a central planning body. PM is its Chairperson."},
{id:"eco05",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"easy",q:"The Green Revolution in India primarily boosted the production of:",opts:["Cotton and jute","Wheat and rice","Tea and coffee","Pulses and oilseeds"],ans:1,exp:"The Green Revolution (1960s-70s) introduced High Yielding Varieties (HYV) of wheat and rice seeds. It was mainly successful in Punjab, Haryana and UP for wheat. Associated with M.S. Swaminathan and Norman Borlaug."},
{id:"eco06",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"medium",q:"Operation Flood was related to:",opts:["Flood relief operations","Development of milk production (White Revolution)","Irrigation schemes","Fishery development"],ans:1,exp:"Operation Flood (1970-1996) — India's White Revolution — was the world's largest dairy development programme. It was spearheaded by Verghese Kurien through AMUL and the National Dairy Development Board (NDDB)."},
{id:"eco07",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"easy",q:"Goods and Services Tax (GST) was implemented in India on:",opts:["1 April 2016","1 July 2017","1 January 2018","26 November 2016"],ans:1,exp:"GST was implemented on 1 July 2017 under the 101st Constitutional Amendment. It replaced multiple indirect taxes. GST has 5 rate slabs: 0%, 5%, 12%, 18%, 28%. GST Council is chaired by Union Finance Minister."},
{id:"eco08",subject:"Economics",cls:"Class 9",topic:"economics",difficulty:"medium",q:"The Human Development Index (HDI) is published by:",opts:["World Bank","IMF","UNDP","WHO"],ans:2,exp:"HDI is published by UNDP (United Nations Development Programme) in the Human Development Report since 1990. It measures: life expectancy, education (mean years of schooling + expected years), and per capita income. Norway consistently tops."},
{id:"eco09",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"medium",q:"NABARD stands for:",opts:["National Agricultural Bank and Rural Development","National Bank for Agriculture and Rural Development","National Association for Banking and Rural Development","National Agricultural Bureau and Regional Development"],ans:1,exp:"NABARD (National Bank for Agriculture and Rural Development) was established on 12 July 1982 based on the recommendations of B. Sivaraman Committee. It provides credit for agriculture and rural development."},
{id:"eco10",subject:"Economics",cls:"Class 12",topic:"economics",difficulty:"hard",q:"Repo Rate is the rate at which:",opts:["RBI borrows from commercial banks","Commercial banks borrow from RBI","Banks lend to each other overnight","Government borrows from RBI"],ans:1,exp:"Repo Rate: Rate at which commercial banks borrow from RBI by selling securities. When RBI increases repo rate, borrowing becomes expensive, reducing inflation. Reverse Repo Rate: rate at which RBI borrows from commercial banks."},
{id:"eco11",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"medium",q:"The World Trade Organization (WTO) was established in:",opts:["1944","1947","1995","1991"],ans:2,exp:"WTO was established on 1 January 1995, replacing GATT (General Agreement on Tariffs and Trade, 1947). WTO promotes free trade, resolves trade disputes, and has 164 member countries. Headquarters: Geneva, Switzerland."},
{id:"eco12",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"easy",q:"MNREGA guarantees how many days of employment to rural households per year?",opts:["50 days","100 days","200 days","365 days"],ans:1,exp:"MGNREGA (Mahatma Gandhi National Rural Employment Guarantee Act, 2005) guarantees 100 days of wage employment per year to rural households. It was renamed from NREGA in 2009. It provides Rs. 220-250/day (varies by state)."},
{id:"eco13",subject:"Economics",cls:"Class 9",topic:"economics",difficulty:"medium",q:"Which of the following is a direct tax?",opts:["GST","Customs duty","Income tax","Excise duty"],ans:2,exp:"Direct taxes are paid directly by the taxpayer to the government: Income Tax, Corporate Tax, Wealth Tax. Indirect taxes are collected by intermediaries and passed on to consumers: GST, Customs duty, Excise duty."},
{id:"eco14",subject:"Economics",cls:"Class 12",topic:"economics",difficulty:"hard",q:"Fiscal deficit is defined as:",opts:["Total revenue minus total expenditure","Total expenditure minus total receipts excluding borrowings","Revenue expenditure minus revenue receipts","Capital expenditure minus capital receipts"],ans:1,exp:"Fiscal Deficit = Total Expenditure – Total Receipts (excluding borrowings). It indicates the total borrowing requirements of the government. Revenue Deficit = Revenue expenditure – Revenue receipts."},
{id:"eco15",subject:"Economics",cls:"Class 10",topic:"economics",difficulty:"easy",q:"Pradhan Mantri Jan Dhan Yojana (PMJDY) is related to:",opts:["Housing for all","Financial inclusion — opening bank accounts for all","Crop insurance","Social security pensions"],ans:1,exp:"PMJDY (launched 28 August 2014) is a financial inclusion scheme to ensure access to financial services (bank accounts, remittance, credit, insurance, pension) to all households. Accounts earn interest and come with a RuPay debit card."},

];
