// ═══════════════════════════════════════════════════════════
// NCERT General Awareness Question Bank for SSC CGL Tier-I
// 50+ High-Yield MCQs: Class 6-10 | Science, History, Polity, Geography
// ═══════════════════════════════════════════════════════════
const NCERT_QS = [

  // ── PHYSICS ──────────────────────────────────────────────
  { id:"ph01", subject:"Physics", cls:"Class 9", topic:"Motion",
    q:"A body is said to be in uniform motion when it covers:",
    opts:["Equal distances in equal intervals of time","Unequal distances in equal intervals of time","Equal distances in unequal intervals of time","Variable speed in equal intervals"],
    ans:0, exp:"Uniform motion means the body covers equal distances in equal time intervals — speed is constant." },

  { id:"ph02", subject:"Physics", cls:"Class 9", topic:"Force & Laws of Motion",
    q:"Newton's Second Law of Motion gives the definition of:",
    opts:["Inertia","Force","Momentum","Velocity"],
    ans:1, exp:"F = ma. Newton's 2nd Law states Force = mass × acceleration, thereby defining the concept of Force." },

  { id:"ph03", subject:"Physics", cls:"Class 9", topic:"Work & Energy",
    q:"What happens to the kinetic energy of an object if its speed is doubled?",
    opts:["Doubles","Triples","Quadruples","Remains same"],
    ans:2, exp:"KE = ½mv². Doubling speed (v → 2v) makes KE = ½m(2v)² = 4 × (½mv²). So KE quadruples." },

  { id:"ph04", subject:"Physics", cls:"Class 9", topic:"Gravitation",
    q:"The value of acceleration due to gravity (g) on Earth's surface is approximately:",
    opts:["6.67 × 10⁻¹¹ m/s²","9.8 m/s²","8.9 m/s²","10.8 m/s²"],
    ans:1, exp:"g ≈ 9.8 m/s² on Earth's surface. G (gravitational constant) = 6.67 × 10⁻¹¹ N m²/kg²." },

  { id:"ph05", subject:"Physics", cls:"Class 10", topic:"Light",
    q:"The phenomenon responsible for the formation of a rainbow is:",
    opts:["Reflection","Refraction","Dispersion","Diffraction"],
    ans:2, exp:"Dispersion — white sunlight splits into 7 colours (VIBGYOR) when passing through water droplets, forming a rainbow." },

  { id:"ph06", subject:"Physics", cls:"Class 10", topic:"Electricity",
    q:"Which device converts electrical energy into mechanical energy?",
    opts:["Generator","Transformer","Electric Motor","Resistor"],
    ans:2, exp:"An Electric Motor converts electrical energy into mechanical (rotational) energy. A Generator does the reverse." },

  { id:"ph07", subject:"Physics", cls:"Class 8", topic:"Sound",
    q:"The speed of sound is maximum in:",
    opts:["Air","Water","Vacuum","Steel"],
    ans:3, exp:"Sound travels fastest in solids. Speed in steel ≈ 5,100 m/s, in water ≈ 1,500 m/s, and in air ≈ 340 m/s." },

  { id:"ph08", subject:"Physics", cls:"Class 10", topic:"Magnetic Effects",
    q:"Fleming's Left Hand Rule is used to find the direction of:",
    opts:["Induced current","Magnetic field","Force on current-carrying conductor","EMF"],
    ans:2, exp:"Fleming's Left Hand Rule gives the direction of force on a current-carrying conductor placed in a magnetic field (used in motors)." },

  // ── CHEMISTRY ─────────────────────────────────────────────
  { id:"ch01", subject:"Chemistry", cls:"Class 8", topic:"Metals & Non-Metals",
    q:"Which of the following is a non-metal that conducts electricity?",
    opts:["Sulphur","Carbon (Graphite)","Phosphorus","Iodine"],
    ans:1, exp:"Graphite (a form of carbon) is the only non-metal that conducts electricity. It is used as electrode material." },

  { id:"ch02", subject:"Chemistry", cls:"Class 9", topic:"Matter",
    q:"Which state of matter has a definite volume but no definite shape?",
    opts:["Solid","Liquid","Gas","Plasma"],
    ans:1, exp:"Liquids have definite volume (particles close together) but no definite shape (they take the shape of the container)." },

  { id:"ch03", subject:"Chemistry", cls:"Class 10", topic:"Chemical Reactions",
    q:"Rusting of iron is an example of which type of chemical reaction?",
    opts:["Decomposition","Displacement","Oxidation","Combination"],
    ans:2, exp:"Rusting (4Fe + 3O₂ + xH₂O → 2Fe₂O₃.xH₂O) is an oxidation reaction where iron combines with oxygen in presence of moisture." },

  { id:"ch04", subject:"Chemistry", cls:"Class 10", topic:"Acids Bases Salts",
    q:"The pH value of pure water at 25°C is:",
    opts:["0","7","14","8"],
    ans:1, exp:"Pure water is neutral with pH = 7. pH < 7 is acidic; pH > 7 is basic/alkaline." },

  { id:"ch05", subject:"Chemistry", cls:"Class 10", topic:"Carbon Compounds",
    q:"Which gas is produced when ethanol undergoes complete combustion?",
    opts:["CO","CO₂ and H₂O","CH₄","H₂"],
    ans:1, exp:"Complete combustion: C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O. Products are carbon dioxide and water." },

  { id:"ch06", subject:"Chemistry", cls:"Class 9", topic:"Atoms & Molecules",
    q:"The atomic number of an element is defined as the number of:",
    opts:["Neutrons in nucleus","Protons in nucleus","Electrons in outer shell","Nucleons in nucleus"],
    ans:1, exp:"Atomic number = number of protons in the nucleus. It uniquely identifies each element in the periodic table." },

  { id:"ch07", subject:"Chemistry", cls:"Class 8", topic:"Coal & Petroleum",
    q:"Which is called 'Black Gold'?",
    opts:["Coal","Petroleum","Natural Gas","Tar"],
    ans:1, exp:"Petroleum is called 'Black Gold' because it is black in colour and extremely valuable as a source of fuel and raw material." },

  { id:"ch08", subject:"Chemistry", cls:"Class 10", topic:"Periodic Table",
    q:"Elements in the same group of the periodic table have the same:",
    opts:["Atomic mass","Number of neutrons","Valence electrons","Atomic number"],
    ans:2, exp:"Elements in the same group have the same number of valence electrons and thus exhibit similar chemical properties." },

  // ── BIOLOGY ──────────────────────────────────────────────
  { id:"bi01", subject:"Biology", cls:"Class 9", topic:"Cell",
    q:"The powerhouse of the cell is:",
    opts:["Nucleus","Ribosome","Mitochondria","Golgi body"],
    ans:2, exp:"Mitochondria produces ATP (energy) through cellular respiration and is hence called the powerhouse of the cell." },

  { id:"bi02", subject:"Biology", cls:"Class 10", topic:"Life Processes",
    q:"In which part of the human body does digestion of fats mainly occur?",
    opts:["Stomach","Small Intestine","Large Intestine","Mouth"],
    ans:1, exp:"Most fat digestion occurs in the small intestine with the help of bile from the liver and lipase from the pancreas." },

  { id:"bi03", subject:"Biology", cls:"Class 10", topic:"Control & Coordination",
    q:"The hormone responsible for the 'Fight or Flight' response is:",
    opts:["Insulin","Thyroxine","Adrenaline","Oestrogen"],
    ans:2, exp:"Adrenaline (Epinephrine) from the adrenal glands triggers the fight-or-flight response — increases heart rate, dilates pupils." },

  { id:"bi04", subject:"Biology", cls:"Class 10", topic:"Heredity & Evolution",
    q:"Who proposed the theory of 'Natural Selection'?",
    opts:["Gregor Mendel","Charles Darwin","Louis Pasteur","Jean-Baptiste Lamarck"],
    ans:1, exp:"Charles Darwin proposed the Theory of Natural Selection in his book 'On the Origin of Species' (1859)." },

  { id:"bi05", subject:"Biology", cls:"Class 8", topic:"Microorganisms",
    q:"Which type of microorganism is responsible for the disease Malaria?",
    opts:["Bacteria","Fungi","Protozoa","Virus"],
    ans:2, exp:"Malaria is caused by Plasmodium (a protozoan), transmitted by the female Anopheles mosquito." },

  { id:"bi06", subject:"Biology", cls:"Class 10", topic:"Reproduction",
    q:"In human females, the fusion of egg and sperm normally takes place in the:",
    opts:["Uterus","Ovary","Fallopian Tube","Vagina"],
    ans:2, exp:"Fertilization (fusion of egg and sperm) normally occurs in the Fallopian tube (oviduct). The fertilized egg then implants in the uterus." },

  { id:"bi07", subject:"Biology", cls:"Class 9", topic:"Tissues",
    q:"Which tissue is responsible for the transport of water and minerals in plants?",
    opts:["Phloem","Xylem","Parenchyma","Collenchyma"],
    ans:1, exp:"Xylem transports water and minerals from roots upward. Phloem transports food (sugars) from leaves to other parts." },

  { id:"bi08", subject:"Biology", cls:"Class 10", topic:"Our Environment",
    q:"Which gas is mainly responsible for the Greenhouse Effect?",
    opts:["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"],
    ans:2, exp:"CO₂ (Carbon Dioxide) is the primary greenhouse gas responsible for global warming and the greenhouse effect." },

  // ── HISTORY ──────────────────────────────────────────────
  { id:"hi01", subject:"History", cls:"Class 6", topic:"Ancient India",
    q:"The Harappan civilization flourished along which river?",
    opts:["Ganga","Yamuna","Indus","Brahmaputra"],
    ans:2, exp:"The Harappan (Indus Valley) Civilization (2600–1900 BCE) flourished along the Indus river and its tributaries." },

  { id:"hi02", subject:"History", cls:"Class 7", topic:"Medieval India",
    q:"Who was the founder of the Mughal Empire in India?",
    opts:["Akbar","Humayun","Babur","Shah Jahan"],
    ans:2, exp:"Babur founded the Mughal Empire after defeating Ibrahim Lodi at the First Battle of Panipat in 1526." },

  { id:"hi03", subject:"History", cls:"Class 8", topic:"Modern India",
    q:"The Revolt of 1857 began at:",
    opts:["Delhi","Lucknow","Meerut","Kanpur"],
    ans:2, exp:"The Revolt of 1857 (First War of Independence) began at Meerut on May 10, 1857, when Indian sepoys revolted against British rule." },

  { id:"hi04", subject:"History", cls:"Class 8", topic:"Modern India",
    q:"The Indian National Congress was founded in which year?",
    opts:["1857","1885","1905","1920"],
    ans:1, exp:"The Indian National Congress (INC) was founded in 1885 by A.O. Hume, Dadabhai Naoroji, and Dinshaw Wacha." },

  { id:"hi05", subject:"History", cls:"Class 8", topic:"Modern India",
    q:"The Partition of Bengal (1905) was done by which Viceroy?",
    opts:["Lord Curzon","Lord Dalhousie","Lord Mountbatten","Lord Wellesley"],
    ans:0, exp:"Lord Curzon partitioned Bengal in 1905 into East and West Bengal, which led to the Swadeshi Movement." },

  { id:"hi06", subject:"History", cls:"Class 8", topic:"Nationalism",
    q:"The Non-Cooperation Movement was launched by Mahatma Gandhi in:",
    opts:["1919","1920","1922","1930"],
    ans:1, exp:"Gandhi launched the Non-Cooperation Movement in 1920. It was withdrawn in 1922 after the Chauri Chaura violence." },

  { id:"hi07", subject:"History", cls:"Class 8", topic:"Nationalism",
    q:"The Dandi March (Salt March) was associated with which movement?",
    opts:["Non-Cooperation Movement","Civil Disobedience Movement","Quit India Movement","Swadeshi Movement"],
    ans:1, exp:"The Dandi March (March 1930) was part of the Civil Disobedience Movement launched by Gandhi against the British salt tax." },

  { id:"hi08", subject:"History", cls:"Class 6", topic:"Ancient Rulers",
    q:"The Ashoka pillar at Sarnath has the emblem that India adopted as its National Emblem. Ashoka was a ruler of which dynasty?",
    opts:["Gupta","Maurya","Chola","Kushan"],
    ans:1, exp:"Ashoka was the third ruler of the Maurya Empire. The Lion Capital of Sarnath (made by Ashoka) is India's National Emblem." },

  // ── POLITY ───────────────────────────────────────────────
  { id:"po01", subject:"Polity", cls:"Class 8", topic:"Constitution",
    q:"The Indian Constitution came into effect on:",
    opts:["15 August 1947","26 November 1949","26 January 1950","2 October 1950"],
    ans:2, exp:"India's Constitution came into force on 26 January 1950. This date is celebrated as Republic Day." },

  { id:"po02", subject:"Polity", cls:"Class 8", topic:"Parliament",
    q:"The Upper House of the Indian Parliament is called:",
    opts:["Lok Sabha","Rajya Sabha","Vidhan Sabha","Vidhan Parishad"],
    ans:1, exp:"Rajya Sabha is the Upper House (Council of States). Lok Sabha is the Lower House (House of the People)." },

  { id:"po03", subject:"Polity", cls:"Class 8", topic:"Fundamental Rights",
    q:"Right to Education for children (6-14 years) is guaranteed under which Article?",
    opts:["Article 14","Article 19","Article 21A","Article 32"],
    ans:2, exp:"Article 21A (added by 86th Amendment, 2002) guarantees free and compulsory education for children aged 6-14 years." },

  { id:"po04", subject:"Polity", cls:"Class 8", topic:"Judiciary",
    q:"Who is the head of the Supreme Court of India?",
    opts:["President","Prime Minister","Chief Justice of India","Attorney General"],
    ans:2, exp:"The Chief Justice of India (CJI) heads the Supreme Court of India, which is the apex judicial body." },

  { id:"po05", subject:"Polity", cls:"Class 9", topic:"Democratic Politics",
    q:"Which system of government does India follow?",
    opts:["Presidential","Parliamentary","Federal with unitary bias","Confederal"],
    ans:1, exp:"India follows a Parliamentary system of government where the executive (Council of Ministers) is responsible to the legislature (Parliament)." },

  { id:"po06", subject:"Polity", cls:"Class 8", topic:"Preamble",
    q:"The word 'Secular' was added to the Indian Constitution's Preamble by which Amendment?",
    opts:["42nd Amendment","44th Amendment","52nd Amendment","74th Amendment"],
    ans:0, exp:"The 42nd Constitutional Amendment (1976) added the words 'Socialist', 'Secular', and 'Integrity' to the Preamble." },

  { id:"po07", subject:"Polity", cls:"Class 9", topic:"Elections",
    q:"The minimum age to vote in Indian general elections is:",
    opts:["16 years","18 years","21 years","25 years"],
    ans:1, exp:"The voting age in India was lowered from 21 to 18 years by the 61st Constitutional Amendment Act, 1988." },

  { id:"po08", subject:"Polity", cls:"Class 8", topic:"Local Government",
    q:"The 73rd Constitutional Amendment (1992) relates to:",
    opts:["Urban Local Bodies","Panchayati Raj","Fundamental Duties","Directive Principles"],
    ans:1, exp:"The 73rd Amendment gave constitutional status to Panchayati Raj institutions (rural local government). The 74th covers Urban Local Bodies." },

  // ── GEOGRAPHY ────────────────────────────────────────────
  { id:"ge01", subject:"Geography", cls:"Class 6", topic:"Solar System",
    q:"Which is the largest planet in our Solar System?",
    opts:["Saturn","Earth","Jupiter","Neptune"],
    ans:2, exp:"Jupiter is the largest planet in the Solar System. It has the Great Red Spot — a storm that has lasted for centuries." },

  { id:"ge02", subject:"Geography", cls:"Class 9", topic:"India — Physical Features",
    q:"The Himalayan river Ganga originates from:",
    opts:["Yamunotri","Gangotri","Kedarnath","Badrinath"],
    ans:1, exp:"River Ganga originates from Gangotri glacier in Uttarkashi, Uttarakhand. The Yamuna originates from Yamunotri." },

  { id:"ge03", subject:"Geography", cls:"Class 9", topic:"Climate",
    q:"The 'Monsoon' in India arrives first at:",
    opts:["Mumbai","Delhi","Kerala","Chennai"],
    ans:2, exp:"The Southwest Monsoon first arrives at Kerala (Thiruvananthapuram) around June 1st and then progresses northward." },

  { id:"ge04", subject:"Geography", cls:"Class 8", topic:"Resources",
    q:"Which state is the largest producer of coal in India?",
    opts:["West Bengal","Odisha","Jharkhand","Madhya Pradesh"],
    ans:2, exp:"Jharkhand is the largest producer of coal in India. Damodar Valley region (Jharia, Bokaro) contains the richest coal deposits." },

  { id:"ge05", subject:"Geography", cls:"Class 9", topic:"Drainage System",
    q:"The river Brahmaputra is called 'Tsangpo' in which country?",
    opts:["Nepal","Bhutan","China (Tibet)","Bangladesh"],
    ans:2, exp:"The Brahmaputra originates in Tibet (China) as Tsangpo, flows through Arunachal Pradesh (as Dihang), and then through Assam." },

  { id:"ge06", subject:"Geography", cls:"Class 7", topic:"Atmosphere",
    q:"The layer of atmosphere that contains the ozone layer is:",
    opts:["Troposphere","Stratosphere","Mesosphere","Thermosphere"],
    ans:1, exp:"The ozone layer is found in the Stratosphere (15-35 km above Earth's surface). It absorbs harmful UV radiation from the Sun." },

  { id:"ge07", subject:"Geography", cls:"Class 9", topic:"India — Location",
    q:"The Tropic of Cancer (23.5°N) passes through how many Indian states?",
    opts:["6","7","8","9"],
    ans:2, exp:"The Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, WB, Tripura, and Mizoram." },

  { id:"ge08", subject:"Geography", cls:"Class 10", topic:"Minerals",
    q:"Which mineral is known as 'Iron Ore of Commerce'?",
    opts:["Magnetite","Haematite","Limonite","Siderite"],
    ans:1, exp:"Haematite (Fe₂O₃) is called Iron Ore of Commerce because it has 60-70% iron content and is the most widely used iron ore." },

  { id:"ge09", subject:"Geography", cls:"Class 10", topic:"Manufacturing Industries",
    q:"Jamshedpur is famous for which industry?",
    opts:["Textile","Iron & Steel","Petrochemical","Sugar"],
    ans:1, exp:"Jamshedpur (Jharkhand) is home to Tata Iron & Steel Company (TISCO), India's first integrated iron and steel plant (est. 1907)." },

  { id:"ge10", subject:"Geography", cls:"Class 9", topic:"Natural Vegetation",
    q:"Sundarbans — the world's largest mangrove forest — is located in:",
    opts:["West Bengal & Odisha","West Bengal & Bangladesh","Andaman Islands","Gujarat"],
    ans:1, exp:"The Sundarbans mangrove forest spans the delta of the Ganga-Brahmaputra and lies across West Bengal (India) and Bangladesh." }
,

  // ── MORE PHYSICS ─────────────────────────────────────────
  { id:"ph09", subject:"Physics", cls:"Class 10", topic:"Light",
    q:"Which type of mirror is used in the headlights of vehicles?",
    opts:["Convex mirror","Concave mirror","Plane mirror","Parabolic convex mirror"],
    ans:1, exp:"Concave mirrors are used in vehicle headlights to get powerful parallel beams of light when the bulb is placed at the focus." },
  { id:"ph10", subject:"Physics", cls:"Class 10", topic:"Electricity",
    q:"What is the SI unit of electrical resistance?",
    opts:["Ampere","Volt","Ohm","Watt"],
    ans:2, exp:"The SI unit of electrical resistance is Ohm (Ω), named after Georg Simon Ohm." },
  { id:"ph11", subject:"Physics", cls:"Class 9", topic:"Sound",
    q:"The audible range of sound for human beings is generally:",
    opts:["20 Hz to 20,000 Hz","10 Hz to 10,000 Hz","200 Hz to 20,000 Hz","20 Hz to 2,000 Hz"],
    ans:0, exp:"Humans can hear sound frequencies ranging from about 20 Hz to 20,000 Hz (20 kHz). Frequencies below 20 Hz are infrasonic, and above 20 kHz are ultrasonic." },

  // ── MORE CHEMISTRY ───────────────────────────────────────
  { id:"ch09", subject:"Chemistry", cls:"Class 10", topic:"Acids Bases Salts",
    q:"Which acid is present in ant sting?",
    opts:["Citric acid","Acetic acid","Methanoic acid","Lactic acid"],
    ans:2, exp:"Ant sting contains methanoic acid (also known as formic acid), which causes pain and irritation." },
  { id:"ch10", subject:"Chemistry", cls:"Class 10", topic:"Carbon Compounds",
    q:"Buckminsterfullerene is an allotropic form of:",
    opts:["Phosphorus","Sulphur","Carbon","Tin"],
    ans:2, exp:"Buckminsterfullerene (C-60) is an allotrope of carbon, structured like a soccer ball." },
  { id:"ch11", subject:"Chemistry", cls:"Class 10", topic:"Metals & Non-Metals",
    q:"Which metal is stored under kerosene oil to prevent accidental fire?",
    opts:["Magnesium","Sodium","Calcium","Zinc"],
    ans:1, exp:"Sodium and potassium are highly reactive and catch fire if exposed to oxygen and moisture in the air. Thus, they are stored under kerosene." },

  // ── MORE BIOLOGY ─────────────────────────────────────────
  { id:"bi09", subject:"Biology", cls:"Class 10", topic:"Life Processes",
    q:"Which component of blood is responsible for clotting?",
    opts:["Red Blood Cells","White Blood Cells","Platelets","Plasma"],
    ans:2, exp:"Platelets (thrombocytes) clump together at the site of a wound to form a plug (clot) and prevent blood loss." },
  { id:"bi10", subject:"Biology", cls:"Class 6", topic:"Components of Food",
    q:"Deficiency of Vitamin C causes which disease?",
    opts:["Rickets","Scurvy","Beri-beri","Night Blindness"],
    ans:1, exp:"Deficiency of Vitamin C causes Scurvy, characterized by bleeding gums. Citrus fruits are rich in Vitamin C." },
  { id:"bi11", subject:"Biology", cls:"Class 10", topic:"Life Processes",
    q:"In plants, what is the role of stomata?",
    opts:["Exchange of gases","Absorption of water","Transport of food","Structural support"],
    ans:0, exp:"Stomata are tiny pores on the surface of leaves used for the exchange of gases (CO2 and O2) and transpiration (loss of water vapor)." },

  // ── MORE HISTORY ─────────────────────────────────────────
  { id:"hi09", subject:"History", cls:"Class 6", topic:"Ancient India",
    q:"Where did Gautama Buddha attain enlightenment?",
    opts:["Sarnath","Bodh Gaya","Lumbini","Kushinagar"],
    ans:1, exp:"Gautama Buddha attained enlightenment under a pipal tree at Bodh Gaya (Bihar). He was born in Lumbini and gave his first sermon at Sarnath." },
  { id:"hi10", subject:"History", cls:"Class 7", topic:"Medieval India",
    q:"Who built the Brihadisvara Temple at Thanjavur?",
    opts:["Rajaraja Chola I","Rajendra Chola I","Krishnadevaraya","Narasimhavarman I"],
    ans:0, exp:"The Brihadisvara Temple (a UNESCO World Heritage site) was built by the great Chola king Rajaraja I in 1010 CE." },
  { id:"hi11", subject:"History", cls:"Class 8", topic:"Modern India",
    q:"The Rowlatt Act was passed in which year?",
    opts:["1905","1917","1919","1922"],
    ans:2, exp:"The Rowlatt Act of 1919 allowed the British government to imprison anyone without a trial, leading to widespread protests and the Jallianwala Bagh massacre." },

  // ── MORE POLITY ──────────────────────────────────────────
  { id:"po09", subject:"Polity", cls:"Class 9", topic:"Electoral Politics",
    q:"Who appoints the Chief Election Commissioner of India?",
    opts:["Prime Minister","Chief Justice of India","President of India","Parliament"],
    ans:2, exp:"The President of India appoints the Chief Election Commissioner and other Election Commissioners." },
  { id:"po10", subject:"Polity", cls:"Class 8", topic:"Constitution",
    q:"The concept of 'Fundamental Duties' in the Indian Constitution was borrowed from:",
    opts:["USA","UK","USSR (Russia)","Ireland"],
    ans:2, exp:"Fundamental Duties were added by the 42nd Amendment (1976) and were inspired by the Constitution of the USSR." },
  { id:"po11", subject:"Polity", cls:"Class 8", topic:"Judiciary",
    q:"What is the retirement age for a Supreme Court Judge in India?",
    opts:["60 years","62 years","65 years","70 years"],
    ans:2, exp:"Judges of the Supreme Court of India retire at the age of 65, while High Court judges retire at 62." },

  // ── MORE GEOGRAPHY ───────────────────────────────────────
  { id:"ge11", subject:"Geography", cls:"Class 10", topic:"Agriculture",
    q:"Which type of soil is ideal for growing cotton in India?",
    opts:["Alluvial Soil","Red Soil","Black Soil","Laterite Soil"],
    ans:2, exp:"Black soil (also known as Regur soil) is ideal for growing cotton, largely found in the Deccan Plateau (Maharashtra, Gujarat)." },
  { id:"ge12", subject:"Geography", cls:"Class 9", topic:"Physical Features",
    q:"The Western Ghats and the Eastern Ghats meet at the:",
    opts:["Cardamom Hills","Nilgiri Hills","Anamalai Hills","Palani Hills"],
    ans:1, exp:"The Eastern Ghats and Western Ghats meet at the Nilgiri Hills in Tamil Nadu." },
  { id:"ge13", subject:"Geography", cls:"Class 9", topic:"Drainage",
    q:"Which is the longest peninsular river in India?",
    opts:["Godavari","Krishna","Kaveri","Narmada"],
    ans:0, exp:"The Godavari is the longest peninsular river (approx 1465 km) and is often called the 'Dakshin Ganga'." }

,

  // ── MASSIVE BATCH: PHYSICS ───────────────────────────────
  { id:"ph12", subject:"Physics", cls:"Class 9", topic:"Work & Energy",
    q:"The commercial unit of electrical energy is kilowatt-hour (kWh). 1 kWh is equal to:",
    opts:["3.6 × 10^5 J","3.6 × 10^6 J","3.6 × 10^4 J","3.6 × 10^7 J"],
    ans:1, exp:"1 kWh = 1000 W × 3600 s = 3.6 × 10^6 Joules." },
  { id:"ph13", subject:"Physics", cls:"Class 10", topic:"Light",
    q:"Power of a lens is measured in:",
    opts:["Meters","Dioptre","Watt","Candela"],
    ans:1, exp:"The SI unit of power of a lens is Dioptre (D). Power P = 1/f (where f is focal length in meters)." },
  { id:"ph14", subject:"Physics", cls:"Class 9", topic:"Motion",
    q:"The slope of a velocity-time graph represents:",
    opts:["Distance","Displacement","Acceleration","Speed"],
    ans:2, exp:"The slope of a velocity-time graph gives acceleration, while the area under it gives displacement." },
  { id:"ph15", subject:"Physics", cls:"Class 9", topic:"Gravitation",
    q:"Weight of an object on the Moon is roughly what fraction of its weight on Earth?",
    opts:["1/2","1/4","1/6","1/10"],
    ans:2, exp:"Gravity on the Moon is about 1/6th of Earth's gravity, so an object weighs 1/6th as much." },
  { id:"ph16", subject:"Physics", cls:"Class 11", topic:"Units & Measurements",
    q:"Light year is a unit of:",
    opts:["Time","Distance","Speed of light","Intensity of light"],
    ans:1, exp:"A light year is the distance travelled by light in a vacuum in one year (approx 9.46 × 10^12 km)." },
  { id:"ph17", subject:"Physics", cls:"Class 10", topic:"Electricity",
    q:"Which alloy is commonly used for making heating elements of electrical appliances like irons and toasters?",
    opts:["Brass","Bronze","Nichrome","Solder"],
    ans:2, exp:"Nichrome (alloy of Ni, Cr, Mn, Fe) is used because of its high resistivity and it does not oxidize easily at high temperatures." },
  { id:"ph18", subject:"Physics", cls:"Class 8", topic:"Friction",
    q:"Which of the following types of friction is the weakest?",
    opts:["Static friction","Sliding friction","Rolling friction","Limiting friction"],
    ans:2, exp:"Rolling friction is the weakest, which is why wheels are used to reduce friction." },

  // ── MASSIVE BATCH: CHEMISTRY ─────────────────────────────
  { id:"ch12", subject:"Chemistry", cls:"Class 9", topic:"Matter",
    q:"The process of conversion of a solid directly into gas without passing through the liquid state is called:",
    opts:["Evaporation","Condensation","Sublimation","Deposition"],
    ans:2, exp:"Sublimation is the direct phase transition from solid to gas (e.g., camphor, dry ice)." },
  { id:"ch13", subject:"Chemistry", cls:"Class 10", topic:"Acids Bases Salts",
    q:"Baking soda is chemically known as:",
    opts:["Sodium carbonate","Sodium bicarbonate","Calcium carbonate","Sodium hydroxide"],
    ans:1, exp:"Baking soda is Sodium Bicarbonate (NaHCO3). Washing soda is Sodium Carbonate (Na2CO3)." },
  { id:"ch14", subject:"Chemistry", cls:"Class 10", topic:"Metals & Non-Metals",
    q:"Bronze is an alloy of:",
    opts:["Copper and Zinc","Copper and Tin","Iron and Carbon","Lead and Tin"],
    ans:1, exp:"Bronze is an alloy of Copper and Tin. Brass is an alloy of Copper and Zinc." },
  { id:"ch15", subject:"Chemistry", cls:"Class 10", topic:"Periodic Table",
    q:"Who is known as the father of the modern periodic table?",
    opts:["Antoine Lavoisier","John Newlands","Dmitri Mendeleev","Henry Moseley"],
    ans:2, exp:"Dmitri Mendeleev is considered the father of the periodic table, though Henry Moseley established the modern periodic law based on atomic number." },
  { id:"ch16", subject:"Chemistry", cls:"Class 10", topic:"Carbon Compounds",
    q:"Which functional group is present in alcohols?",
    opts:["-OH","-COOH","-CHO","-CO-"],
    ans:0, exp:"Alcohols contain the hydroxyl (-OH) functional group." },
  { id:"ch17", subject:"Chemistry", cls:"Class 9", topic:"Atoms & Molecules",
    q:"What is the chemical formula of quicklime?",
    opts:["CaCO3","Ca(OH)2","CaO","CaCl2"],
    ans:2, exp:"Quicklime is Calcium Oxide (CaO). Slaked lime is Calcium Hydroxide (Ca(OH)2)." },
  { id:"ch18", subject:"Chemistry", cls:"Class 8", topic:"Synthetic Fibres",
    q:"Which of the following is known as 'artificial silk'?",
    opts:["Nylon","Rayon","Polyester","Acrylic"],
    ans:1, exp:"Rayon is synthesized from wood pulp and has properties similar to silk, hence called artificial silk." },

  // ── MASSIVE BATCH: BIOLOGY ───────────────────────────────
  { id:"bi12", subject:"Biology", cls:"Class 10", topic:"Control & Coordination",
    q:"Which part of the human brain controls involuntary actions like blood pressure and vomiting?",
    opts:["Cerebrum","Cerebellum","Medulla","Hypothalamus"],
    ans:2, exp:"The Medulla oblongata in the hindbrain controls involuntary vital functions like heartbeat, blood pressure, and vomiting." },
  { id:"bi13", subject:"Biology", cls:"Class 9", topic:"Tissues",
    q:"The connective tissue that connects muscle to bone is called:",
    opts:["Ligament","Tendon","Cartilage","Areolar tissue"],
    ans:1, exp:"Tendons connect muscles to bones, whereas Ligaments connect bones to other bones." },
  { id:"bi14", subject:"Biology", cls:"Class 10", topic:"Life Processes",
    q:"What is the functional unit of the human kidney?",
    opts:["Neuron","Nephron","Alveoli","Villi"],
    ans:1, exp:"The Nephron is the microscopic structural and functional unit of the kidney responsible for filtering blood." },
  { id:"bi15", subject:"Biology", cls:"Class 9", topic:"Diversity",
    q:"Which group of plants is known as the 'amphibians of the plant kingdom'?",
    opts:["Thallophyta","Bryophyta","Pteridophyta","Gymnosperms"],
    ans:1, exp:"Bryophytes (like mosses) are called amphibians of the plant kingdom because they live on land but need water for sexual reproduction." },
  { id:"bi16", subject:"Biology", cls:"Class 6", topic:"Components of Food",
    q:"Goitre is caused by the deficiency of:",
    opts:["Iron","Calcium","Iodine","Vitamin D"],
    ans:2, exp:"Deficiency of iodine leads to Goitre, which is the abnormal enlargement of the thyroid gland in the neck." },
  { id:"bi17", subject:"Biology", cls:"Class 8", topic:"Cell Structure",
    q:"Which organelle is known as the 'suicide bag' of the cell?",
    opts:["Lysosome","Ribosome","Vacuole","Plastid"],
    ans:0, exp:"Lysosomes contain powerful digestive enzymes. If the cell is damaged, lysosomes may burst and digest their own cell, hence 'suicide bags'." },
  { id:"bi18", subject:"Biology", cls:"Class 10", topic:"Life Processes",
    q:"The normal systolic and diastolic blood pressure of a healthy human is:",
    opts:["120/80 mm Hg","80/120 mm Hg","140/90 mm Hg","100/60 mm Hg"],
    ans:0, exp:"Normal blood pressure is 120 mm Hg (systolic) over 80 mm Hg (diastolic)." },
  { id:"bi19", subject:"Biology", cls:"Class 10", topic:"Life Processes",
    q:"Bile juice is secreted by which organ?",
    opts:["Stomach","Pancreas","Liver","Gall bladder"],
    ans:2, exp:"The Liver secretes bile juice, which is temporarily stored in the gall bladder before being released into the small intestine." },

  // ── MASSIVE BATCH: HISTORY ───────────────────────────────
  { id:"hi12", subject:"History", cls:"Class 7", topic:"Delhi Sultanate",
    q:"Who was the first female ruler of the Delhi Sultanate?",
    opts:["Nur Jahan","Razia Sultana","Chand Bibi","Mumtaz Mahal"],
    ans:1, exp:"Razia Sultana (daughter of Iltutmish) was the first and only female ruler of the Delhi Sultanate (1236-1240)." },
  { id:"hi13", subject:"History", cls:"Class 8", topic:"Modern India",
    q:"The permanent settlement of Bengal was introduced by:",
    opts:["Lord Cornwallis","Lord Wellesley","Lord Hastings","Lord Dalhousie"],
    ans:0, exp:"Lord Cornwallis introduced the Permanent Settlement in Bengal and Bihar in 1793 to fix land revenue." },
  { id:"hi14", subject:"History", cls:"Class 6", topic:"Ancient India",
    q:"The Gayatri Mantra is contained in which Veda?",
    opts:["Rig Veda","Sama Veda","Yajur Veda","Atharva Veda"],
    ans:0, exp:"The Gayatri Mantra, dedicated to the solar deity Savitri, is found in the 3rd Mandala of the Rig Veda." },
  { id:"hi15", subject:"History", cls:"Class 8", topic:"Nationalism",
    q:"Who gave the slogan 'Do or Die' during the Quit India Movement?",
    opts:["Subhas Chandra Bose","Mahatma Gandhi","Jawaharlal Nehru","Bhagat Singh"],
    ans:1, exp:"Mahatma Gandhi gave the 'Do or Die' (Karo ya Maro) slogan during the launch of the Quit India Movement in 1942." },
  { id:"hi16", subject:"History", cls:"Class 8", topic:"Nationalism",
    q:"Who is known as the 'Frontier Gandhi'?",
    opts:["Maulana Abul Kalam Azad","Khan Abdul Ghaffar Khan","Lala Lajpat Rai","Bal Gangadhar Tilak"],
    ans:1, exp:"Khan Abdul Ghaffar Khan (Bacha Khan), leader of the Khudai Khidmatgars, was known as Frontier Gandhi." },
  { id:"hi17", subject:"History", cls:"Class 7", topic:"Medieval India",
    q:"The battle of Haldighati (1576) was fought between Akbar and:",
    opts:["Hemu","Maharana Pratap","Shivaji","Rana Sanga"],
    ans:1, exp:"The Battle of Haldighati was fought in 1576 between the Mughal forces led by Man Singh I and Maharana Pratap of Mewar." },
  { id:"hi18", subject:"History", cls:"Class 8", topic:"Modern India",
    q:"Who founded the 'Brahmo Samaj'?",
    opts:["Swami Vivekananda","Dayanand Saraswati","Raja Ram Mohan Roy","Ishwar Chandra Vidyasagar"],
    ans:2, exp:"Raja Ram Mohan Roy founded the Brahmo Samaj in 1828 and campaigned against Sati and child marriage." },

  // ── MASSIVE BATCH: POLITY ────────────────────────────────
  { id:"po12", subject:"Polity", cls:"Class 8", topic:"Constitution",
    q:"Which Article of the Indian Constitution abolishes 'Untouchability'?",
    opts:["Article 14","Article 15","Article 16","Article 17"],
    ans:3, exp:"Article 17 of the Indian Constitution abolishes the practice of untouchability in any form." },
  { id:"po13", subject:"Polity", cls:"Class 9", topic:"Parliament",
    q:"What is the maximum strength of the Lok Sabha as per the Constitution?",
    opts:["545","550","552","543"],
    ans:2, exp:"The maximum strength of Lok Sabha is 552 (530 from States, 20 from UTs, 2 historically nominated Anglo-Indians)." },
  { id:"po14", subject:"Polity", cls:"Class 8", topic:"Constitution",
    q:"Which Schedule of the Indian Constitution contains the list of recognized languages?",
    opts:["6th Schedule","7th Schedule","8th Schedule","9th Schedule"],
    ans:2, exp:"The 8th Schedule lists the 22 officially recognized languages of the Republic of India." },
  { id:"po15", subject:"Polity", cls:"Class 8", topic:"Panchayati Raj",
    q:"What is the middle tier in the three-tier Panchayati Raj system?",
    opts:["Gram Panchayat","Panchayat Samiti","Zila Parishad","Gram Sabha"],
    ans:1, exp:"The Panchayat Samiti operates at the block level, forming the middle tier between Gram Panchayat (village) and Zila Parishad (district)." },
  { id:"po16", subject:"Polity", cls:"Class 9", topic:"President",
    q:"Under which Article can the President declare a National Emergency?",
    opts:["Article 352","Article 356","Article 360","Article 370"],
    ans:0, exp:"Article 352 allows the President to declare a National Emergency on grounds of war, external aggression, or armed rebellion." },
  { id:"po17", subject:"Polity", cls:"Class 8", topic:"Constitution",
    q:"Who is the ex-officio Chairman of the Rajya Sabha?",
    opts:["President of India","Prime Minister","Vice-President of India","Speaker of Lok Sabha"],
    ans:2, exp:"The Vice-President of India serves as the ex-officio Chairman of the Rajya Sabha." },

  // ── MASSIVE BATCH: GEOGRAPHY ─────────────────────────────
  { id:"ge14", subject:"Geography", cls:"Class 9", topic:"India - Size & Location",
    q:"Which water body separates India and Sri Lanka?",
    opts:["Palk Strait","Malacca Strait","Bering Strait","Gibraltar Strait"],
    ans:0, exp:"India and Sri Lanka are separated by the Palk Strait and the Gulf of Mannar." },
  { id:"ge15", subject:"Geography", cls:"Class 9", topic:"Climate",
    q:"El Niño is a weather phenomenon associated with the warming of which ocean?",
    opts:["Atlantic Ocean","Indian Ocean","Pacific Ocean","Arctic Ocean"],
    ans:2, exp:"El Niño is the abnormal warming of surface waters in the eastern tropical Pacific Ocean, which affects global weather patterns, including Indian monsoons." },
  { id:"ge16", subject:"Geography", cls:"Class 8", topic:"Resources",
    q:"Which of the following is the leading producer of copper in India?",
    opts:["Rajasthan","Madhya Pradesh","Jharkhand","Karnataka"],
    ans:1, exp:"Madhya Pradesh (Balaghat mines) is the leading producer of copper in India, followed by Rajasthan (Khetri)." },
  { id:"ge17", subject:"Geography", cls:"Class 11", topic:"Physical Geography",
    q:"What is the name of the boundary line between India and China?",
    opts:["Radcliffe Line","Durand Line","McMahon Line","Maginot Line"],
    ans:2, exp:"The McMahon Line forms the boundary between India (Arunachal Pradesh) and China (Tibet)." },
  { id:"ge18", subject:"Geography", cls:"Class 9", topic:"Drainage",
    q:"Which river is known as the 'Sorrow of Bihar'?",
    opts:["Ganga","Kosi","Damodar","Son"],
    ans:1, exp:"The Kosi river is called the Sorrow of Bihar due to its frequent and devastating floods." },
  { id:"ge19", subject:"Geography", cls:"Class 6", topic:"Earth",
    q:"The longest day in the Northern Hemisphere occurs on:",
    opts:["March 21","June 21","September 23","December 22"],
    ans:1, exp:"June 21 is the Summer Solstice, the longest day in the Northern Hemisphere." },
  { id:"ge20", subject:"Geography", cls:"Class 10", topic:"Agriculture",
    q:"Which of these is a Rabi crop?",
    opts:["Rice","Maize","Wheat","Cotton"],
    ans:2, exp:"Wheat is a Rabi (winter) crop, sown in Oct-Dec and harvested in Apr-Jun. Rice, Maize, and Cotton are Kharif (monsoon) crops." },

  // ── MASSIVE BATCH: ECONOMICS (Common in SSC) ─────────────
  { id:"ec01", subject:"Economics", cls:"Class 10", topic:"Sectors of Economy",
    q:"Banking, transportation, and communication fall under which sector of the economy?",
    opts:["Primary Sector","Secondary Sector","Tertiary Sector","Quaternary Sector"],
    ans:2, exp:"Services like banking, transport, and IT form the Tertiary (service) sector." },
  { id:"ec02", subject:"Economics", cls:"Class 9", topic:"Money & Credit",
    q:"The Reserve Bank of India (RBI) was established in which year?",
    opts:["1935","1947","1949","1950"],
    ans:0, exp:"The RBI was established on April 1, 1935, under the Reserve Bank of India Act, 1934. It was nationalized in 1949." },
  { id:"ec03", subject:"Economics", cls:"Class 11", topic:"Indian Economy",
    q:"Who is known as the Father of the White Revolution in India?",
    opts:["M.S. Swaminathan","Verghese Kurien","Norman Borlaug","Homi Bhabha"],
    ans:1, exp:"Dr. Verghese Kurien (Operation Flood) is the Father of the White Revolution (milk production). M.S. Swaminathan led the Green Revolution in India." },
  { id:"ec04", subject:"Economics", cls:"Class 12", topic:"Macroeconomics",
    q:"What does 'GDP' stand for?",
    opts:["Gross Domestic Product","General Domestic Product","Gross Domestic Price","Gross Dividend Profit"],
    ans:0, exp:"GDP stands for Gross Domestic Product, the total monetary value of all finished goods and services produced within a country's borders in a specific time." },
  { id:"ec05", subject:"Economics", cls:"Class 11", topic:"Indian Economy",
    q:"NITI Aayog replaced which institution in India?",
    opts:["Finance Commission","Planning Commission","National Development Council","Election Commission"],
    ans:1, exp:"NITI Aayog (National Institution for Transforming India) replaced the Planning Commission on January 1, 2015." }

,

  // ── MASSIVE BATCH 3: MIXED SUBJECTS ──────────────────────
  { id:"ph19", subject:"Physics", cls:"Class 10", topic:"Light",
    q:"The splitting of white light into its component colors is called:",
    opts:["Refraction","Reflection","Dispersion","Scattering"],
    ans:2, exp:"Dispersion is the splitting of white light into 7 colors (VIBGYOR), usually demonstrated using a glass prism." },
  { id:"ph20", subject:"Physics", cls:"Class 9", topic:"Gravitation",
    q:"The value of universal gravitational constant (G) is:",
    opts:["6.67 x 10^-11 Nm^2/kg^2","9.8 m/s^2","3 x 10^8 m/s","6.022 x 10^23"],
    ans:0, exp:"G is the universal gravitational constant, approximately equal to 6.674 × 10^-11 N⋅m^2/kg^2." },
  { id:"ch19", subject:"Chemistry", cls:"Class 10", topic:"Chemical Reactions",
    q:"Rancidity of food containing fats and oils can be prevented by adding:",
    opts:["Antacids","Antioxidants","Catalysts","Indicators"],
    ans:1, exp:"Antioxidants (like BHA and BHT) are added to foods containing fats and oils to prevent oxidation (rancidity)." },
  { id:"ch20", subject:"Chemistry", cls:"Class 9", topic:"Structure of Atom",
    q:"Isotopes of an element have:",
    opts:["Same physical properties","Different number of protons","Different number of neutrons","Different atomic number"],
    ans:2, exp:"Isotopes have the same atomic number (protons) but a different mass number (neutrons)." },
  { id:"bi20", subject:"Biology", cls:"Class 10", topic:"Reproduction",
    q:"Vegetative propagation refers to the formation of new plants from:",
    opts:["Stem, roots, and leaves","Flowers and seeds","Only seeds","Fruits"],
    ans:0, exp:"Vegetative propagation is an asexual reproduction method where new plants grow from stems, roots, or leaves." },
  { id:"bi21", subject:"Biology", cls:"Class 9", topic:"Diseases",
    q:"Which of the following diseases is caused by a virus?",
    opts:["Cholera","Typhoid","Tuberculosis","Dengue"],
    ans:3, exp:"Dengue is caused by the Dengue virus transmitted by the Aedes mosquito. The others are bacterial." },
  { id:"hi19", subject:"History", cls:"Class 6", topic:"Ancient India",
    q:"Who was the court physician of Kanishka?",
    opts:["Sushruta","Charaka","Patanjali","Jivaka"],
    ans:1, exp:"Charaka, one of the principal contributors to Ayurveda (Charaka Samhita), was the court physician of Kanishka." },
  { id:"hi20", subject:"History", cls:"Class 8", topic:"Modern India",
    q:"The Vernacular Press Act was passed in 1878 by:",
    opts:["Lord Lytton","Lord Ripon","Lord Curzon","Lord Dalhousie"],
    ans:0, exp:"Lord Lytton passed the Vernacular Press Act in 1878 to suppress the Indian-language press from criticizing British policies." },
  { id:"po18", subject:"Polity", cls:"Class 8", topic:"Constitution",
    q:"The Directive Principles of State Policy (DPSP) in the Indian Constitution are taken from the constitution of:",
    opts:["Britain","USA","Ireland","Canada"],
    ans:2, exp:"DPSP (Part IV of the Constitution) was borrowed from the Irish Constitution." },
  { id:"po19", subject:"Polity", cls:"Class 8", topic:"Constitution",
    q:"Which Article of the Constitution gives the power to amend the Constitution to the Parliament?",
    opts:["Article 356","Article 368","Article 370","Article 32"],
    ans:1, exp:"Article 368 in Part XX of the Constitution deals with the powers of Parliament to amend the Constitution and its procedure." },
  { id:"ge21", subject:"Geography", cls:"Class 9", topic:"Climate",
    q:"Which is the wettest place on Earth?",
    opts:["Cherrapunji","Mawsynram","Agumbe","Mahabaleshwar"],
    ans:1, exp:"Mawsynram in the Khasi Hills of Meghalaya, India, is recognized as the wettest place on Earth." },
  { id:"ge22", subject:"Geography", cls:"Class 10", topic:"Minerals",
    q:"Bauxite is an ore of which metal?",
    opts:["Iron","Aluminum","Copper","Zinc"],
    ans:1, exp:"Bauxite is the primary ore from which Aluminum is extracted." },
  { id:"ec06", subject:"Economics", cls:"Class 11", topic:"Indian Economy",
    q:"Which sector contributes the most to India's GDP?",
    opts:["Primary (Agriculture)","Secondary (Industry)","Tertiary (Services)","Quaternary"],
    ans:2, exp:"The Tertiary (Services) sector is the largest contributor to India's Gross Domestic Product (GDP)." },
  { id:"ec07", subject:"Economics", cls:"Class 9", topic:"Poverty",
    q:"What is the accepted average calorie requirement in India for rural areas per person per day?",
    opts:["2100 calories","2400 calories","2000 calories","2500 calories"],
    ans:1, exp:"The accepted average calorie requirement is 2400 calories per person per day in rural areas and 2100 calories in urban areas." }

];
