// Rajbhasha MCQ Data — IIT Tirupati Translation Competition
// Question Bank I (Vocabulary + Spelling) + Question Bank II (Noting & Sentence Translation)

window.rajbhashaQuiz = [
  {"id":"rb_1","bank":"QB-I: Vocabulary","question":"अंग्रेजी शब्द 'Notification' का सही राजभाषा अनुवाद क्या है?","options":["सूचना","अधिसूचना","विज्ञापन","ज्ञापन"],"correct":1},
  {"id":"rb_2","bank":"QB-I: Vocabulary","question":"अंग्रेजी शब्द 'Memorandum' के लिए प्रयुक्त मानक हिंदी शब्द कौन-सा है?","options":["ज्ञापन","प्रतिवेदन","परिपत्र","संचिका"],"correct":0},
  {"id":"rb_3","bank":"QB-I: Vocabulary","question":"'Endorsement' का प्रशासनिक हिंदी अनुवाद क्या होगा?","options":["पृष्ठांकन","अनुलग्नक","स्वीकृति","अनुमोदन"],"correct":0},
  {"id":"rb_4","bank":"QB-I: Vocabulary","question":"'Competent Authority' के लिए आधिकारिक हिंदी पद क्या है?","options":["उच्च अधिकारी","सक्षम प्राधिकारी","मुख्य अधिकारी","प्रशासनिक अधिकारी"],"correct":1},
  {"id":"rb_5","bank":"QB-I: Vocabulary","question":"'Honorarium' शब्द का सही हिंदी पर्याय चुनिए:","options":["वेतन","मानदेय","भत्ता","पारिश्रमिक"],"correct":1},
  {"id":"rb_6","bank":"QB-I: Vocabulary","question":"'Deputation' शब्द का राजभाषा में क्या अनुवाद होता है?","options":["प्रतिनियुक्ति","स्थानांतरण","पदोन्नति","नियुक्ति"],"correct":0},
  {"id":"rb_7","bank":"QB-I: Vocabulary","question":"'Probation' के लिए मानक प्रशासनिक शब्द क्या है?","options":["परिवीक्षा","प्रशिक्षण","परीक्षण","मूल्यांकन"],"correct":0},
  {"id":"rb_8","bank":"QB-I: Vocabulary","question":"'Circular' के लिए आधिकारिक हिंदी शब्द क्या है?","options":["नियमावली","परिपत्र","सूचना","आदेश"],"correct":1},
  {"id":"rb_9","bank":"QB-I: Vocabulary","question":"'Ex-Officio' पद का सही हिंदी अनुवाद कौन-सा है?","options":["तदर्थ","पदेन","अस्थायी","मुख्य"],"correct":1},
  {"id":"rb_10","bank":"QB-I: Vocabulary","question":"'Audit' का केंद्र सरकार के कार्यालयों में मानक अनुवाद क्या है?","options":["लेखापरीक्षा","लेखाजोखा","वित्तीय समीक्षा","समाशोधन"],"correct":0},
  {"id":"rb_11","bank":"QB-I: Vocabulary","question":"'Enclosure' शब्द के लिए उपयुक्त हिंदी शब्द क्या है?","options":["अनुलग्नक","परिशिष्ट","अनुक्रमणिका","विवरण"],"correct":0},
  {"id":"rb_12","bank":"QB-I: Vocabulary","question":"'Vigilance' का सही प्रशासनिक अनुवाद चुनिए:","options":["सतर्कता","गोपनीयता","तटस्थता","सुरक्षा"],"correct":0},
  {"id":"rb_13","bank":"QB-I: Vocabulary","question":"'Grievance' के लिए आधिकारिक हिंदी शब्द क्या है?","options":["शिकायत / व्यथा","समीक्षा","सुझाव","अपील"],"correct":0},
  {"id":"rb_14","bank":"QB-I: Vocabulary","question":"'Cabinet' शब्द का राजभाषा अनुवाद क्या होगा?","options":["मंत्रिमंडल","विधानमंडल","सचिवालय","परिषद"],"correct":0},
  {"id":"rb_15","bank":"QB-I: Vocabulary","question":"'Backlog' शब्द का सही हिंदी पर्याय क्या है?","options":["पिछला ब्यौरा","बकाया","अग्रिम","शेष राशि"],"correct":1},
  {"id":"rb_16","bank":"QB-I: Vocabulary","question":"'Quorum' के लिए राजभाषा में प्रयुक्त मानक शब्द चुनिए:","options":["गणपूर्ति","बहुमत","उपस्थिति","समिति"],"correct":0},
  {"id":"rb_17","bank":"QB-I: Vocabulary","question":"'Cadre' शब्द का सही हिंदी अनुवाद क्या है?","options":["संवर्ग","श्रेणी","वर्ग","पदनाम"],"correct":0},
  {"id":"rb_18","bank":"QB-I: Vocabulary","question":"'Disciplinary Action' का आधिकारिक हिंदी अनुवाद क्या है?","options":["प्रशासनिक कार्रवाई","अनुशासनिक कार्रवाई","कानूनी कार्रवाई","विभागीय जांच"],"correct":1},
  {"id":"rb_19","bank":"QB-I: Vocabulary","question":"'Gazetted Officer' के लिए उपयुक्त हिंदी पदनाम क्या है?","options":["राजपत्रित अधिकारी","मुख्य अधिकारी","वरिष्ठ अधिकारी","प्रशासनिक अधिकारी"],"correct":0},
  {"id":"rb_20","bank":"QB-I: Vocabulary","question":"'Allowance' शब्द का सही हिंदी अनुवाद क्या है?","options":["मानदेय","भत्ता","वेतन","बोनस"],"correct":1},
  {"id":"rb_21","bank":"QB-I: Spelling","question":"'Notification' के लिए शुद्ध हिंदी वर्तनी का चयन कीजिए:","options":["अधिसुचना","अधिसूचना","आधिसूचना","अधिसुछना"],"correct":1},
  {"id":"rb_22","bank":"QB-I: Spelling","question":"'Administrative' के लिए शुद्ध वर्तनी वाला विकल्प चुनिए:","options":["प्रशाधनिक","प्राशासनिक","प्रशासनिक","प्रशासनीक"],"correct":2},
  {"id":"rb_23","bank":"QB-I: Spelling","question":"'Deputation' का सही एवं शुद्ध वर्तनी वाला रूप कौन-सा है?","options":["प्रतिनियुती","प्रतीनियुक्ति","प्रतिनियुक्ति","प्रतीनीयुक्ती"],"correct":2},
  {"id":"rb_24","bank":"QB-I: Spelling","question":"'Probation' के लिए शुद्ध हिंदी वर्तनी चुनिए:","options":["परिवीक्षा","परिधिक्षा","परीधिक्षा","परीवीक्षा"],"correct":0},
  {"id":"rb_25","bank":"QB-I: Spelling","question":"'Endorsement' के लिए सही वर्तनी वाला शब्द कौन-सा है?","options":["पृष्ठांकन","धृष्टांकन","प्रष्टाकन","पृष्टांकन"],"correct":0},
  {"id":"rb_26","bank":"QB-I: Spelling","question":"'Authority' के लिए शुद्ध वर्तनी का चयन कीजिए:","options":["प्राधिकारी","प्राधिकारि","प्रधिकारी","परधिकारी"],"correct":0},
  {"id":"rb_27","bank":"QB-I: Spelling","question":"'Cabinet' के लिए शुद्ध वर्तनी वाला रूप चुनिए:","options":["मंत्रीमंडल","मंत्रिमंडल","मन्त्रीमण्डल","मधन्त्रिंमण्डल"],"correct":1},
  {"id":"rb_28","bank":"QB-I: Spelling","question":"'Disciplinary' का सही वर्तनी रूप कौन-सा है?","options":["अनुशासनीक","अनुसाशनिक","अनुशासनिक","आनुशासनिक"],"correct":2},
  {"id":"rb_29","bank":"QB-I: Spelling","question":"'Honorarium' के लिए शुद्ध हिंदी वर्तनी चुनिए:","options":["मानदेय","मानदैय","मानदेया","मानदए"],"correct":0},
  {"id":"rb_30","bank":"QB-I: Spelling","question":"'Gazetted' के लिए सही वर्तनी वाला विकल्प चुनिए:","options":["राजपत्रीत","राजपत्रित","राजपत्रीित","राजपत्रीधि"],"correct":1},
  {"id":"rb_31","bank":"QB-I: Spelling","question":"'Enclosure' के लिए शुद्ध वर्तनी का चयन कीजिए:","options":["अनुलगणक","अनुलग्नक","अनुलाग्नक","अनूलग्नक"],"correct":1},
  {"id":"rb_32","bank":"QB-I: Spelling","question":"'Vigilance' के लिए सही वर्तनी रूप चुनिए:","options":["सिरकथा","सतर्कता","सतकाथत्ता","सतवकता"],"correct":1},
  {"id":"rb_33","bank":"QB-I: Spelling","question":"'Quorum' के लिए शुद्ध हिंदी वर्तनी चुनिए:","options":["गणपुती","गणपूर्ति","गनपूधि","गणपुतधि"],"correct":1},
  {"id":"rb_34","bank":"QB-I: Spelling","question":"'Recommendation' के लिए सही वर्तनी का चयन कीजिए:","options":["संस्तुती","संस्तुति","संसतुधि","संसाधुधि"],"correct":1},
  {"id":"rb_35","bank":"QB-I: Spelling","question":"'Audit' के लिए शुद्ध वर्तनी वाला विकल्प चुनिए:","options":["लेखापरीछा","लेखापरिक्षा","लेखापरीक्षा","लेकापरीक्षा"],"correct":2},
  {"id":"rb_36","bank":"QB-I: Spelling","question":"'Cadre' के लिए सही वर्तनी वाला रूप कौन-सा है?","options":["संवर्ग","संवरग","सावर्ग","संवरगा"],"correct":0},
  {"id":"rb_37","bank":"QB-I: Spelling","question":"'Implementation' के लिए शुद्ध हिंदी वर्तनी चुनिए:","options":["कार्यान्वयन","कार्यानियन","कार्यान्यवन","कार्यांनियन"],"correct":0},
  {"id":"rb_38","bank":"QB-I: Spelling","question":"'Acquisition' के लिए सही वर्तनी का चयन कीजिए:","options":["अधिग्रहण","अधिग्रहन","आधिग्रहण","अधिधिग्रहण"],"correct":0},
  {"id":"rb_39","bank":"QB-I: Spelling","question":"'Transfer' के लिए शुद्ध वर्तनी वाला विकल्प चुनिए:","options":["स्थानांतरण","स्थानान्तरन","स्थानांन्तरण","स्थानांतंरण"],"correct":0},
  {"id":"rb_40","bank":"QB-I: Spelling","question":"'Approval' के लिए सही वर्तनी वाला रूप चुनिए:","options":["धिस्तकृधि","स्वीकृति","स्वीकृती","धिस्तकृती"],"correct":1},
  {"id":"rb_41","bank":"QB-II: Noting","question":"'For information and necessary action' का मानक अनुवाद क्या है?","options":["सूचना और काम के लिए","सूचनार्थ एवं आवश्यक कार्रवाई हेतु","सूचना और आगे की प्रक्रिया","जानकारी और कार्रवाई के लिए"],"correct":1},
  {"id":"rb_42","bank":"QB-II: Noting","question":"'Submitted for perusal' का सही हिंदी अनुवाद क्या है?","options":["पढ़ने के लिए भेजा गया","अवलोकनार्थ प्रस्तुत","जांच के लिए लिया गया","देखने हेतु प्रस्तुत"],"correct":1},
  {"id":"rb_43","bank":"QB-II: Noting","question":"'May kindly be approved' का मानक टिप्पणी वाक्य कौन-सा है?","options":["कृपया पास किया जाए","कृपया अनुमोदित किया जाए","कृपया स्वीकार करें","कृपया मान लिया जाए"],"correct":1},
  {"id":"rb_44","bank":"QB-II: Noting","question":"'As proposed above' के लिए मानक हिंदी टिप्पणी क्या होगी?","options":["जैसा ऊपर लिखा है","यथाप्रस्तावित ऊपर","जैसा ऊपर प्रस्तावित है","उपयुक्त प्रस्ताव अनुसार"],"correct":2},
  {"id":"rb_45","bank":"QB-II: Noting","question":"'Issue as drafted' का हिंदी अनुवाद क्या है?","options":["ड्राफ्ट जारी करें","प्रारूपानुसार जारी करें","जैसा बना है जारी करें","पत्र जारी किया जाए"],"correct":1},
  {"id":"rb_46","bank":"QB-II: Noting","question":"'Submitted for consideration' के लिए आधिकारिक टिप्पणी पद क्या है?","options":["विचार के लिए भेजा","विचारार्थ प्रस्तुत","सोचने हेतु प्रस्तुत","निर्णय हेतु लिया"],"correct":1},
  {"id":"rb_47","bank":"QB-II: Noting","question":"'Action as per rules may be taken' का प्रशासनिक अनुवाद क्या है?","options":["नियम से काम करो","नियमानुसार कार्रवाई की जाए","नियम देखकर काम करें","कानूनन कार्रवाई करें"],"correct":1},
  {"id":"rb_48","bank":"QB-II: Noting","question":"'Keep on file' के लिए नोटिंग में किस वाक्य का प्रयोग होता है?","options":["फाइल में रखें","नस्तीबद्ध करें","फाइल बंद करें","कागज़ जमा करें"],"correct":1},
  {"id":"rb_49","bank":"QB-II: Noting","question":"'For orders, please' का आधिकारिक हिंदी पर्याय क्या है?","options":["आदेश के लिए कृपया","आदेशार्थ प्रस्तुत","आदेश लिया जाए","कृपया आदेश दें"],"correct":1},
  {"id":"rb_50","bank":"QB-II: Noting","question":"'Compliance report may be sent' का सही अनुवाद चुनिए:","options":["पालन रिपोर्ट भेजें","अनुपालन रिपोर्ट भेजी जाए","काम की रिपोर्ट भेजें","पूर्णता रिपोर्ट दें"],"correct":1},
  {"id":"rb_51","bank":"QB-II: Noting","question":"'Draft for approval is put up' का सही हिंदी अनुवाद क्या है?","options":["पास करने हेतु ड्राफ्ट रखा है","अनुमोदन हेतु प्रारूप प्रस्तुत है","स्वीकृति के लिए पत्र लिया है","ड्राफ्ट मंजूरी के लिए लाया गया"],"correct":1},
  {"id":"rb_52","bank":"QB-II: Noting","question":"'Copy is enclosed' का मानक नोटिंग अनुवाद क्या है?","options":["कॉपी साथ में है","प्रति संलग्न है","पर्चा साथ जुड़ा है","प्रतिलिपि पीछे है"],"correct":1},
  {"id":"rb_53","bank":"QB-II: Noting","question":"'Subject to approval' के लिए उपयुक्त हिंदी टिप्पणी क्या है?","options":["मंजूरी के हिसाब से","अनुमोदन के अधीन","स्वीकृति के आधार पर","पास होने की शर्त पर"],"correct":1},
  {"id":"rb_54","bank":"QB-II: Noting","question":"'Approved as proposed' का सही अनुवाद चुनिए:","options":["जैसे कहा गया पास है","यथाप्रस्तावित अनुमोदित","प्रस्ताव अनुसार ठीक है","मन्जूर किया गया"],"correct":1},
  {"id":"rb_55","bank":"QB-II: Noting","question":"'May be discussed' के लिए आधिकारिक टिप्पणी वाक्य क्या है?","options":["बातचीत करें","चर्चा की जा सकती है / चर्चा करें","सलाह दें","मीटिंग बुलाएं"],"correct":1},
  {"id":"rb_56","bank":"QB-II: Noting","question":"'Put up with previous papers' का मानक अनुवाद क्या है?","options":["पुराने कागज़ों के साथ रखें","पूर्व पत्रों के साथ प्रस्तुत करें","पिछली फाइल लाएं","पुराने पत्र साथ जोड़ें"],"correct":1},
  {"id":"rb_57","bank":"QB-II: Noting","question":"'Sanction is hereby accorded' का आधिकारिक अनुवाद क्या है?","options":["मंजूरी दे दी गई है","एतद्वारा स्वीकृति प्रदान की जाती है","स्वीकृति पास होती है","आदेश लिया जाता है"],"correct":1},
  {"id":"rb_58","bank":"QB-II: Noting","question":"'Please speak' (नोटिंग पर लिखा) का क्या अर्थ है?","options":["कृपया बोलें","कृपया बात करें","भाषण दें","मौखिक बताएं"],"correct":1},
  {"id":"rb_59","bank":"QB-II: Noting","question":"'Action taken report' का मानक प्रशासनिक अनुवाद क्या है?","options":["काम की रिपोर्ट","की गई कार्रवाई की रिपोर्ट","कार्रवाई विवरण","अंतिम रिपोर्ट"],"correct":1},
  {"id":"rb_60","bank":"QB-II: Noting","question":"'Interim reply may be sent' का सही अर्थ क्या है?","options":["बीच का उत्तर भेजें","अंतरिम उत्तर भेजा जाए","तुरंत उत्तर दें","छोटा जवाब भेजें"],"correct":1},
  {"id":"rb_61","bank":"QB-II: Noting","question":"'May be treated as cancelled' का मानक अनुवाद क्या है?","options":["रद्द मान लिया जाए","निरस्त / रद्द समझा जाए","खत्म किया जाए","वापस लिया जाए"],"correct":1},
  {"id":"rb_62","bank":"QB-II: Noting","question":"'In terms of rules' के लिए उपयुक्त हिंदी वाक्य क्या है?","options":["नियम की शर्तों पर","नियमों के अनुसार","नियम के आधार पर","नियम देखते हुए"],"correct":1},
  {"id":"rb_63","bank":"QB-II: Noting","question":"'Ex-post facto approval may be granted' का अनुवाद क्या है?","options":["बाद की मंजूरी दें","कायोत्तर अनुमोदन प्रदान किया जाए","पुराना अनुमोदन दें","पिछला पास करें"],"correct":1},
  {"id":"rb_64","bank":"QB-II: Noting","question":"'Matter may be expedited' के लिए टिप्पणी वाक्य क्या होगा?","options":["मामले में तेज़ी लाएं","मामले को शीघ्र निपटाया जाए","काम जल्दी करें","फाइल तुरंत आगे बढ़ाएं"],"correct":1},
  {"id":"rb_65","bank":"QB-II: Noting","question":"'No further action is required' का सही अनुवाद क्या है?","options":["अब कोई काम नहीं है","आगे किसी कार्रवाई की आवश्यकता नहीं है","अब कार्रवाई बंद करें","फाइल बंद कर दें"],"correct":1},
  {"id":"rb_66","bank":"QB-II: Noting","question":"'Suitable reply may be sent' का मानक टिप्पणी अनुवाद क्या है?","options":["सही जवाब भेजें","उपयुक्त उत्तर भेजा जाए","जैसा ठीक लगे जवाब दें","अच्छा उत्तर दें"],"correct":1},
  {"id":"rb_67","bank":"QB-II: Noting","question":"'For strict compliance' का मानक हिंदी रूप क्या है?","options":["सख्त पालन के लिए","कड़ाई से अनुपालन हेतु","पक्का पालन करें","नियम पालन के लिए"],"correct":1},
  {"id":"rb_68","bank":"QB-II: Noting","question":"'Bring to the notice of' का सही हिंदी अर्थ क्या है?","options":["ध्यान में लाया जाए","सूचना में दें","नोटिस भेजें","जानकारी बढ़ाएं"],"correct":0},
  {"id":"rb_69","bank":"QB-II: Noting","question":"'Till further orders' के लिए आधिकारिक टिप्पणी वाक्य क्या है?","options":["अगले आदेश तक","अगले आदेशों तक","नए आदेश आने तक","जब तक आदेश न आए"],"correct":1},
  {"id":"rb_70","bank":"QB-II: Noting","question":"'Orders are awaited' का मानक अनुवाद क्या है?","options":["आदेश आने वाले हैं","आदेशों की प्रतीक्षा है","आदेश का इंतज़ार है","आदेश रुके हुए हैं"],"correct":1},
  {"id":"rb_71","bank":"QB-II: Noting","question":"'As desired by high authority' का हिंदी अनुवाद क्या होगा?","options":["जैसा उच्च अधिकारी ने चाहा","उच्च प्राधिकारी के निदेशानुसार / इच्छानुसार","बड़े साहब के कहने पर","उच्च अधिकारी के आदेश से"],"correct":1},
  {"id":"rb_72","bank":"QB-II: Noting","question":"'Detailed report is awaited' का सही हिंदी अर्थ चुनिए:","options":["बड़ी रिपोर्ट आनी है","विस्तृत रिपोर्ट की प्रतीक्षा है","पूरी रिपोर्ट का इंतज़ार है","विस्तृत रिपोर्ट भेजी जाए"],"correct":1},
  {"id":"rb_73","bank":"QB-II: Noting","question":"'Remind later' के लिए संक्षिप्त टिप्पणी वाक्य क्या होगा?","options":["बाद में याद दिलाएं","बाद में स्मरण दिलाएं","फिर से पूछें","बाद में फाइल लाएं"],"correct":1},
  {"id":"rb_74","bank":"QB-II: Noting","question":"'For perusal only' का राजभाषा अनुवाद क्या है?","options":["सिर्फ पढ़ने के लिए","केवल अवलोकनार्थ","देखने भर के लिए","केवल जांच हेतु"],"correct":1},
  {"id":"rb_75","bank":"QB-II: Noting","question":"'File may be closed' के लिए प्रयुक्त मानक टिप्पणी वाक्य क्या है?","options":["फाइल बंद की जाए","नस्ती दाखिल दफ्तर की जाए","फाइल जमा करें","नस्ती खत्म की जाए"],"correct":1},
  {"id":"rb_76","bank":"QB-II: Noting","question":"'Seen and returned' के लिए मानक हिंदी टिप्पणी क्या है?","options":["देखा और वापस किया","देखा और लौटाया गया","देख लिया गया है","जांच कर वापस भेजा"],"correct":1},
  {"id":"rb_77","bank":"QB-II: Noting","question":"'In continuation of our letter' का सही राजभाषा अनुवाद क्या है?","options":["हमारे पत्र के आगे","हमारे पत्र के क्रम में","पत्र के साथ में","पिछले पत्र के अनुसार"],"correct":1},
  {"id":"rb_78","bank":"QB-II: Noting","question":"'Clarification may be sought' का मानक टिप्पणी अनुवाद क्या होगा?","options":["सफाई मांगी जाए","स्पष्टीकरण मांगा जाए","कारण पूछा जाए","जवाब तलब किया जाए"],"correct":1},
  {"id":"rb_79","bank":"QB-II: Noting","question":"'Matter is under consideration' का हिंदी अनुवाद क्या है?","options":["मामला विचाराधीन है","बात चल रही है","मामले पर सोच रहे हैं","निर्णय लिया जा रहा है"],"correct":0},
  {"id":"rb_80","bank":"QB-II: Noting","question":"'As amended from time to time' का मानक अनुवाद क्या है?","options":["जैसा समय पर बदला गया","समय-समय पर यथा संशोधित","समय अनुसार बदला हुआ","समय-समय पर परिमार्जित"],"correct":1},
  {"id":"rb_81","bank":"QB-II: Noting","question":"'Strictly confidential' का मानक टिप्पणी अनुवाद क्या है?","options":["बहुत गुप्त","पूर्णतः गोपनीय","खास गोपनीय","अत्यंत व्यक्तिगत"],"correct":1},
  {"id":"rb_82","bank":"QB-II: Noting","question":"'Acknowledged with thanks' का सही अर्थ चुनिए:","options":["धन्यवाद के साथ मिला","सधन्यवाद स्वीकार किया गया","शुक्रिया के साथ प्राप्त","धन्यवाद रसीद भेजी गई"],"correct":1},
  {"id":"rb_83","bank":"QB-II: Noting","question":"'Put up on fresh page' के लिए मानक हिंदी आदेश क्या है?","options":["नए पन्ने पर लिखें","नए पृष्ठ पर प्रस्तुत करें","साफे कागज़ पर लाएं","अगले पन्ने पर रखें"],"correct":1},
  {"id":"rb_84","bank":"QB-II: Noting","question":"'Approved subject to availability of funds' का अनुवाद क्या है?","options":["पैसा होने पर पास होगा","निधि/बजट की उपलब्धता के अधीन अनुमोदित","बजट मिलने पर मंजूर","फंड देखकर पास करें"],"correct":1},
  {"id":"rb_85","bank":"QB-II: Noting","question":"'Early reply is requested' का मानक प्रशासनिक अनुवाद क्या है?","options":["जल्दी जवाब दें","शीघ्र उत्तर का अनुरोध है","तुरंत उत्तर भेजें","जल्दी उत्तर की आशा है"],"correct":1},
  {"id":"rb_86","bank":"QB-II: Noting","question":"'Forwarded for necessary action' का अनुवाद क्या होगा?","options":["काम के लिए भेजा","आवश्यक कार्रवाई हेतु अग्रेषित","आगे कार्रवाई के लिए लिया","आवश्यक काम के लिए बढ़ाएं"],"correct":1},
  {"id":"rb_87","bank":"QB-II: Noting","question":"'Matter is urgent' का सही टिप्पणी रूप चुनिए:","options":["मामला जरूरी है","मामला अत्यावश्यक है","काम तुरंत करें","विषय आपातकालीन है"],"correct":1},
  {"id":"rb_88","bank":"QB-II: Noting","question":"'Information is awaited' का मानक अनुवाद क्या है?","options":["जानकारी आनी बाकी है","सूचना की प्रतीक्षा है","खबर का इंतज़ार है","जानकारी जल्द आएगी"],"correct":1},
  {"id":"rb_89","bank":"QB-II: Noting","question":"'As per rules' के लिए संक्षिप्त टिप्पणी शब्द क्या है?","options":["नियम अनुसार","नियमानुसार","नियम देखकर","नियम के तहत"],"correct":1},
  {"id":"rb_90","bank":"QB-II: Noting","question":"'File is submitted herewith' का मानक हिंदी रूप क्या है?","options":["फाइल साथ में दी जा रही है","नस्ती इसके साथ प्रस्तुत है","फाइल संलग्न कर भेजी है","कागज़ात साथ रखे हैं"],"correct":1}
];

// Merge into window.jjaData once it loads
if (window.jjaData) {
    window.jjaData.rajbhashaQuiz = window.rajbhashaQuiz;
} else {
    document.addEventListener('DOMContentLoaded', function() {
        if (window.jjaData) window.jjaData.rajbhashaQuiz = window.rajbhashaQuiz;
    });
}
