// ═══════════════════════════════════════════════════════════
// English Vocabulary Data for SSC CGL Tier-I
// One-Word Substitutions | Idioms & Phrases | Misspelled Words
// ═══════════════════════════════════════════════════════════
const VOCAB_DATA = [

  // ── ONE-WORD SUBSTITUTIONS (cat: ows) ────────────────────
  { cat:"ows", front:"One who can use both hands with equal ease", back:"Ambidextrous", ex:"An ambidextrous cricketer can bat equally well from both sides." },
  { cat:"ows", front:"Fear of crowds or open spaces", back:"Agoraphobia", ex:"She suffered from agoraphobia and avoided large public gatherings." },
  { cat:"ows", front:"One who studies the evolution of mankind", back:"Anthropologist", ex:"An anthropologist studies human societies, cultures, and their development." },
  { cat:"ows", front:"A person who is unable to sleep", back:"Insomniac", ex:"He was a chronic insomniac who hadn't slept properly in weeks." },
  { cat:"ows", front:"Words written on a tombstone", back:"Epitaph", ex:"The epitaph on the grave read: 'Beloved father, forever in our hearts.'" },
  { cat:"ows", front:"Government by the people", back:"Democracy", ex:"India is the world's largest democracy." },
  { cat:"ows", front:"One who eats both plants and animals", back:"Omnivore", ex:"Humans are omnivores — they eat both plant and animal foods." },
  { cat:"ows", front:"A person who is new to a job or activity", back:"Novice / Neophyte", ex:"As a novice driver, he was still learning basic traffic rules." },
  { cat:"ows", front:"A place where animals are kept for public display", back:"Zoo / Menagerie", ex:"A menagerie was once used to refer to a private collection of exotic animals." },
  { cat:"ows", front:"Murder of one's own mother", back:"Matricide", ex:"The ancient Greek myth of Orestes involves matricide." },
  { cat:"ows", front:"Murder of one's own father", back:"Patricide", ex:"Patricide is considered one of the gravest crimes across cultures." },
  { cat:"ows", front:"Murder of one's own brother", back:"Fratricide", ex:"Many ancient battles were cases of fratricide — brothers killing brothers." },
  { cat:"ows", front:"A person who speaks many languages", back:"Polyglot", ex:"The UN interpreter was a polyglot, fluent in seven languages." },
  { cat:"ows", front:"A remedy for all diseases and difficulties", back:"Panacea", ex:"Education is often cited as the panacea for poverty." },
  { cat:"ows", front:"One who is all-knowing (omniscient) and all-powerful", back:"Omniscient / Omnipotent", ex:"God is described as omniscient and omnipotent in most religions." },
  { cat:"ows", front:"A place where bees are kept", back:"Apiary", ex:"The beekeeper maintained a large apiary in his backyard." },
  { cat:"ows", front:"Writing that cannot be read", back:"Illegible", ex:"The doctor's prescription was so illegible that the pharmacist called to confirm." },
  { cat:"ows", front:"One who pretends to be what one is not", back:"Hypocrite", ex:"Calling oneself honest while cheating others makes one a hypocrite." },
  { cat:"ows", front:"A person who is unable to pay debts", back:"Insolvent / Bankrupt", ex:"After the business failure, he was declared insolvent by the court." },
  { cat:"ows", front:"Something that lasts for a very short time", back:"Ephemeral / Transient", ex:"The ephemeral beauty of cherry blossoms lasts only a week." },
  { cat:"ows", front:"A group of stars forming a recognizable pattern", back:"Constellation", ex:"Orion is one of the most easily recognizable constellations in the night sky." },
  { cat:"ows", front:"One who believes in no god", back:"Atheist", ex:"An atheist lacks belief in the existence of any god or gods." },
  { cat:"ows", front:"A book written by the author about their own life", back:"Autobiography", ex:"Mahatma Gandhi's autobiography is titled 'The Story of My Experiments with Truth.'" },
  { cat:"ows", front:"Murder of a human being by another", back:"Homicide", ex:"The court charged him with first-degree homicide." },
  { cat:"ows", front:"One who is filled with excessive enthusiasm for religion", back:"Fanatic / Zealot", ex:"A religious zealot refuses to tolerate any other belief system." },

  // ── IDIOMS & PHRASES (cat: idioms) ─────────────────────────
  { cat:"idioms", front:"A blessing in disguise", back:"Something that seems bad at first, but turns out to be good", ex:"Missing the bus was a blessing in disguise — I met my future business partner on the next one." },
  { cat:"idioms", front:"Beat around the bush", back:"To avoid coming to the main point", ex:"Stop beating around the bush and tell me what really happened." },
  { cat:"idioms", front:"Bite the bullet", back:"To endure a painful or difficult situation bravely", ex:"He bit the bullet and sat through three hours of dentist appointments." },
  { cat:"idioms", front:"Burning the midnight oil", back:"Working or studying late into the night", ex:"She was burning the midnight oil to finish the project before the deadline." },
  { cat:"idioms", front:"Catch someone red-handed", back:"To discover someone in the act of doing something wrong", ex:"The thief was caught red-handed while stealing from the shop." },
  { cat:"idioms", front:"Cost an arm and a leg", back:"Very expensive", ex:"That luxury watch costs an arm and a leg." },
  { cat:"idioms", front:"Hit the nail on the head", back:"To describe exactly what is causing a situation or problem", ex:"You hit the nail on the head when you said the team lacked communication." },
  { cat:"idioms", front:"Let the cat out of the bag", back:"To accidentally reveal a secret", ex:"She let the cat out of the bag about the surprise party." },
  { cat:"idioms", front:"Once in a blue moon", back:"Very rarely", ex:"He only calls his parents once in a blue moon." },
  { cat:"idioms", front:"Spill the beans", back:"To reveal secret information", ex:"Who spilled the beans about our plan to leave early?" },
  { cat:"idioms", front:"The ball is in your court", back:"It is your decision or responsibility to act next", ex:"I've made my offer — the ball is in your court now." },
  { cat:"idioms", front:"Under the weather", back:"Feeling ill or unwell", ex:"I'm feeling a bit under the weather today — I might skip the gym." },
  { cat:"idioms", front:"A piece of cake", back:"Something very easy to do", ex:"The first round of the exam was a piece of cake." },
  { cat:"idioms", front:"Bite off more than you can chew", back:"To take on a task that is too big for you", ex:"By accepting four projects simultaneously, he bit off more than he could chew." },
  { cat:"idioms", front:"Cut corners", back:"To do something improperly to save time or money", ex:"The contractor cut corners during construction, which caused the building to collapse." },
  { cat:"idioms", front:"Hit the sack", back:"To go to bed", ex:"I'm exhausted — I'm going to hit the sack early tonight." },
  { cat:"idioms", front:"Kick the bucket", back:"A humorous/slang way to say someone has died", ex:"The old television finally kicked the bucket last night." },
  { cat:"idioms", front:"Pull someone's leg", back:"To tease or joke with someone", ex:"Don't worry — I was just pulling your leg! You passed the exam." },
  { cat:"idioms", front:"Sitting on the fence", back:"Being neutral; not taking sides in a dispute", ex:"Stop sitting on the fence — tell us whose plan you think is better." },
  { cat:"idioms", front:"The last straw", back:"The final problem in a series that makes a situation unbearable", ex:"His constant tardiness was the last straw — the boss finally fired him." },
  { cat:"idioms", front:"Throw in the towel", back:"To give up; admit defeat", ex:"After losing the third set, the tennis player threw in the towel." },
  { cat:"idioms", front:"Turn a blind eye", back:"To ignore something that you know is wrong", ex:"The corrupt officer turned a blind eye to the smuggling operation." },
  { cat:"idioms", front:"Add fuel to the fire", back:"To make a bad situation worse", ex:"His angry reply only added fuel to the fire during the argument." },
  { cat:"idioms", front:"Barking up the wrong tree", back:"To look for something in the wrong place or to blame the wrong person", ex:"If you think I took your book, you're barking up the wrong tree." },
  { cat:"idioms", front:"Break the ice", back:"To do or say something to relieve tension or awkwardness", ex:"He told a joke to break the ice at the start of the meeting." },

  // ── COMMONLY MISSPELLED WORDS (cat: spell) ─────────────────
  { cat:"spell", front:"Correct spelling: Accommodate or Accomodate?", back:"Accommodate", ex:"The hotel can accommodate up to 500 guests. (Double 'c' and double 'm')" },
  { cat:"spell", front:"Correct spelling: Occurrence or Occurence?", back:"Occurrence", ex:"This is a rare occurrence in nature. (Double 'c' and double 'r')" },
  { cat:"spell", front:"Correct spelling: Supersede or Supercede?", back:"Supersede", ex:"The new law will supersede the old one. (Never 'cede' — only 'sede')" },
  { cat:"spell", front:"Correct spelling: Separate or Seperate?", back:"Separate", ex:"Please separate the papers into two piles." },
  { cat:"spell", front:"Correct spelling: Definitely or Definately?", back:"Definitely", ex:"I will definitely attend the function tomorrow." },
  { cat:"spell", front:"Correct spelling: Embarrass or Embarass?", back:"Embarrass", ex:"He was embarrassed by his mistake. (Double 'r' and double 's')" },
  { cat:"spell", front:"Correct spelling: Necessary or Neccessary?", back:"Necessary", ex:"It is necessary to wear a helmet while riding. (One 'c', two 's')" },
  { cat:"spell", front:"Correct spelling: Millennium or Millenium?", back:"Millennium", ex:"The new millennium began on January 1, 2001. (Double 'l' and double 'n')" },
  { cat:"spell", front:"Correct spelling: Conscientious or Consientious?", back:"Conscientious", ex:"A conscientious employee always meets deadlines." },
  { cat:"spell", front:"Correct spelling: Bureaucracy or Beaurocracy?", back:"Bureaucracy", ex:"Excessive bureaucracy can slow down government processes." },
  { cat:"spell", front:"Correct spelling: Liaison or Liason?", back:"Liaison", ex:"The officer acted as a liaison between the two departments." },
  { cat:"spell", front:"Correct spelling: Rhythm or Rythm?", back:"Rhythm", ex:"She has a natural sense of rhythm and loves to dance." },
  { cat:"spell", front:"Correct spelling: Colleague or Collegue?", back:"Colleague", ex:"My colleague helped me finish the report on time." },
  { cat:"spell", front:"Correct spelling: Believe or Beleive?", back:"Believe", ex:"I believe you can achieve anything you set your mind to. (i before e after b)" },
  { cat:"spell", front:"Correct spelling: Privilege or Priviledge?", back:"Privilege", ex:"It is a privilege to serve the nation in uniform." }
];
